<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PointsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('points')->insert(['id' => '1', 'name' => ' KR 11 6 106', 'cost_center' => 'ALMT0915', 'trade_name' => 'Fr. Leticia', 'city_id' => '1']);
        DB::table('points')->insert(['id' => '2', 'name' => 'C.C Plaza Del Rio LC 123 CL 100 KR 100 Via Principal Apartado', 'cost_center' => 'ALMT0937', 'trade_name' => 'Plaza del Rio', 'city_id' => '2']);
        DB::table('points')->insert(['id' => '3', 'name' => 'KR 99 N° 84 - 18 Vía Carepa  LC 0165-0167', 'cost_center' => 'ALMT0830', 'trade_name' => 'Nuestro Uraba', 'city_id' => '2']);
        DB::table('points')->insert(['id' => '4', 'name' => 'DG 55 34 67 ', 'cost_center' => 'ALMT1242', 'trade_name' => 'Yoi Éxito Puerta del Norte', 'city_id' => '3']);
        DB::table('points')->insert(['id' => '5', 'name' => 'dirección', 'cost_center' => 'ALMT0913', 'trade_name' => 'Caldas 2', 'city_id' => '4']);
        DB::table('points')->insert(['id' => '6', 'name' => 'dirección', 'cost_center' => 'ALMT0950', 'trade_name' => 'Fr. El Carmen de Viboral', 'city_id' => '5']);
        DB::table('points')->insert(['id' => '7', 'name' => 'dirección', 'cost_center' => 'ALMT1167', 'trade_name' => 'Viva Envigado', 'city_id' => '6']);
        DB::table('points')->insert(['id' => '8', 'name' => 'dirección', 'cost_center' => 'ALMT0967', 'trade_name' => 'Fr. Girardota', 'city_id' => '7']);
        DB::table('points')->insert(['id' => '9', 'name' => 'dirección', 'cost_center' => 'ALMT0923', 'trade_name' => 'Fr. La Ceja', 'city_id' => '8']);
        DB::table('points')->insert(['id' => '10', 'name' => 'CL 15 18 274 LC 145 C.C VIVA LA CEJA ', 'cost_center' => 'ALMT0883', 'trade_name' => 'Viva la Ceja', 'city_id' => '9']);
        DB::table('points')->insert(['id' => '11', 'name' => 'dirección', 'cost_center' => 'ALMT1004', 'trade_name' => 'Fr. La Estrella', 'city_id' => '10']);
        DB::table('points')->insert(['id' => '12', 'name' => 'dirección', 'cost_center' => 'ALMT0990', 'trade_name' => 'Fr. Marinilla', 'city_id' => '11']);
        DB::table('points')->insert(['id' => '13', 'name' => 'Av las vegas N° 50 sur 128 LC 2021 C.C Mayorca Mega Plaza', 'cost_center' => 'ALMT0837', 'trade_name' => 'Mayorca', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '14', 'name' => 'C.C. Outlet Guayabal LC 04', 'cost_center' => 'ALMT0761', 'trade_name' => 'Guayabal', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '15', 'name' => 'C.C. Premiun Plaza LC 2302', 'cost_center' => 'ALMT0405', 'trade_name' => 'Premium Plaza', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '16', 'name' => 'CL 37 No. 50 – 36', 'cost_center' => 'ALMT0420', 'trade_name' => 'La 33', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '17', 'name' => 'CL 51 No. 51-19 Barrio Perez  ', 'cost_center' => 'ALMT0603', 'trade_name' => 'Bello', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '18', 'name' => 'CL 16  55 129 LC  106  C.C De moda outlet ', 'cost_center' => 'ALMT1181', 'trade_name' => 'Moda Prime', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '19', 'name' => 'CL 34 46 66 C.C San Diego LC 1551', 'cost_center' => 'ALMT1231', 'trade_name' => 'San Diego', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '20', 'name' => 'Cl 49 N° 21-38 LC 0214 B. Buenos Aires', 'cost_center' => 'ALMT1151', 'trade_name' => 'La Central', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '21', 'name' => 'Cll 53 No. 47-52', 'cost_center' => 'ALMT0492', 'trade_name' => 'Junin', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '22', 'name' => 'KR 46 # 52- 85 LC 130 ', 'cost_center' => 'ALMT0919', 'trade_name' => 'Camino Real', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '23', 'name' => 'KR 52D # 80-37', 'cost_center' => 'ALMT0877', 'trade_name' => 'Itagui', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '24', 'name' => 'dirección', 'cost_center' => 'ALMT0833', 'trade_name' => 'Aventura', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '25', 'name' => 'dirección', 'cost_center' => 'ALMT1007', 'trade_name' => 'Fr. Caucasia', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '26', 'name' => 'dirección', 'cost_center' => 'ALMT0988', 'trade_name' => 'Fr. Copacabana', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '27', 'name' => 'dirección', 'cost_center' => 'ALMT0931', 'trade_name' => 'Mayorca Dos', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '28', 'name' => '  CL 10 43 E 135 ', 'cost_center' => 'ALTM1249', 'trade_name' => 'Yoi Éxito Poblado', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '29', 'name' => 'KR 66 49 01 ', 'cost_center' => 'ALTMT1245', 'trade_name' => 'Yoi Éxito Colombia', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '30', 'name' => 'KR 66 B 34 A 76', 'cost_center' => 'ALMT1241', 'trade_name' => 'Yoi Éxito Unicentro', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '31', 'name' => 'dirección', 'cost_center' => 'ALMT1001', 'trade_name' => 'Fr. Puerto Berrio', 'city_id' => '13']);
        DB::table('points')->insert(['id' => '32', 'name' => 'C.C. San Nicolás CL 43 No. 54-139 LC 3307', 'cost_center' => 'ALMT0783', 'trade_name' => 'San Nicolas', 'city_id' => '14']);
        DB::table('points')->insert(['id' => '33', 'name' => 'KR 48A No. 50-77 LC 107', 'cost_center' => 'ALMT0586', 'trade_name' => 'Rionegro', 'city_id' => '14']);
        DB::table('points')->insert(['id' => '34', 'name' => 'dirección', 'cost_center' => 'ALMT1023', 'trade_name' => 'Fr. Sabaneta', 'city_id' => '15']);
        DB::table('points')->insert(['id' => '35', 'name' => 'CL 14 16 40', 'cost_center' => 'ALMT0968', 'trade_name' => 'Fr. Tame', 'city_id' => '16']);
        DB::table('points')->insert(['id' => '36', 'name' => 'KR 18 N° 21 - 46 Br. Córdoba', 'cost_center' => 'ALMT0921', 'trade_name' => 'Fr. Arauca', 'city_id' => '16']);
        DB::table('points')->insert(['id' => '37', 'name' => 'CL 31 N° 83b - 104 C.C. San Fernando, LC 121', 'cost_center' => 'ALMT0737', 'trade_name' => 'San Fernando', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '38', 'name' => 'CL 53 N° 46 - 192 LC 006 Sotano C.C Portal del Prado', 'cost_center' => 'ALMT1017', 'trade_name' => 'Prado', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '39', 'name' => 'KR 51b # 87-50 LC 340', 'cost_center' => 'ALMT0893', 'trade_name' => 'Viva Barranquilla', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '40', 'name' => 'CL 30 13 65 LC 1121', 'cost_center' => 'ALMT1163', 'trade_name' => 'Carnaval', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '41', 'name' => 'CL 63 13-71 LC 1013 Soledad', 'cost_center' => 'ALMT0932', 'trade_name' => 'Nuestro Atlántico', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '42', 'name' => 'CL 78 53 70  N 233', 'cost_center' => 'ALMT0796', 'trade_name' => 'Villa Country', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '43', 'name' => 'KR 28 No 58 -148 LC 203', 'cost_center' => 'ALMT0570', 'trade_name' => 'Metropolitano', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '44', 'name' => 'KR 41D No 74-87 C.C. Único L -107 ', 'cost_center' => 'ALMT0410', 'trade_name' => 'Único Barranquilla', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '45', 'name' => 'KR 41D No 74-87 C.C. Único L -73', 'cost_center' => 'ALMT0411', 'trade_name' => 'Único', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '46', 'name' => 'CL 72 52 36 LC 9', 'cost_center' => 'ALMT0628', 'trade_name' => 'Bquila Cll 72', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '47', 'name' => 'CL 14 Diagonal 34-01 LC 107', 'cost_center' => 'ALMT1156', 'trade_name' => 'Buenavista', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '48', 'name' => 'CL 19 19 08 LC 5', 'cost_center' => 'ALMT0992', 'trade_name' => 'Fr. Sabanalarga', 'city_id' => '18']);
        DB::table('points')->insert(['id' => '49', 'name' => 'CL 15 No.11c-75 - Via oriental Km21 Santo Tomas Atlántico', 'cost_center' => 'ALMT1014', 'trade_name' => 'Poblado Plaza', 'city_id' => '19']);
        DB::table('points')->insert(['id' => '50', 'name' => 'KR 37 No 30-33 LC 154 C.C. Gran Plaza Del Sol.', 'cost_center' => 'ALMT0692', 'trade_name' => 'Soledad', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '51', 'name' => 'AV Pedro de heredia, CL 30 30 31 Sector Villa Sandra LC 93-94', 'cost_center' => 'ALMT1209', 'trade_name' => 'La Castellana', 'city_id' => '21']);
        DB::table('points')->insert(['id' => '52', 'name' => 'Bocagrande KR 2 N° 5 - 85 C.C. Nao LC 28', 'cost_center' => 'ALMT0716', 'trade_name' => 'Nao', 'city_id' => '21']);
        DB::table('points')->insert(['id' => '53', 'name' => 'C.C Mall Plaza Av. Pedro De Heredia 13  65 Lc 122-123 Brr Chambacú', 'cost_center' => 'ALMT0936', 'trade_name' => 'Mall Plaza Cartagena', 'city_id' => '21']);
        DB::table('points')->insert(['id' => '54', 'name' => 'C.C. Caribe Plaza LC N° 79 - 80. Barrio la Popa', 'cost_center' => 'ALMT0409', 'trade_name' => 'Cartagena', 'city_id' => '21']);
        DB::table('points')->insert(['id' => '55', 'name' => 'Centro KR 7 N° 34 - 84', 'cost_center' => 'ALMT0814', 'trade_name' => 'Calle Carretas', 'city_id' => '21']);
        DB::table('points')->insert(['id' => '56', 'name' => 'KR 2 # 06-105 LC 0104', 'cost_center' => 'ALMT1184', 'trade_name' => 'Bocagrande', 'city_id' => '21']);
        DB::table('points')->insert(['id' => '57', 'name' => 'TV43. Barrio Nuevo Bosque LC 3', 'cost_center' => 'ALMT0646', 'trade_name' => 'El Bosque', 'city_id' => '21']);
        DB::table('points')->insert(['id' => '58', 'name' => 'CL 34 # 41-19', 'cost_center' => 'ALMT1125', 'trade_name' => 'Paseo Bolívar', 'city_id' => '21']);
        DB::table('points')->insert(['id' => '59', 'name' => 'KR 10 16 23 LC 101', 'cost_center' => 'ALMT0887', 'trade_name' => 'Fr. Chiquinquira', 'city_id' => '22']);
        DB::table('points')->insert(['id' => '60', 'name' => 'CL 12 4 18 LC 3', 'cost_center' => 'ALMT0969', 'trade_name' => 'Fr. Puerto Boyaca', 'city_id' => '23']);
        DB::table('points')->insert(['id' => '61', 'name' => 'Cll15 No 15-52', 'cost_center' => 'ALMT0845', 'trade_name' => 'Duitama Centro', 'city_id' => '24']);
        DB::table('points')->insert(['id' => '62', 'name' => ' CL 11 # 11 - 45 Edf. San Judas Tadeo', 'cost_center' => 'ALMT0895', 'trade_name' => 'Sogamoso', 'city_id' => '25']);
        DB::table('points')->insert(['id' => '63', 'name' => 'AV Universitaria 50 – 21 C.C. Viva LC 128  ', 'cost_center' => 'ALMT1180', 'trade_name' => 'Viva Tunja', 'city_id' => '26']);
        DB::table('points')->insert(['id' => '64', 'name' => 'AV Universitario No 39-77 C.C Unicentro Tunja LC 1019', 'cost_center' => 'ALMT0402', 'trade_name' => 'Tunja', 'city_id' => '26']);
        DB::table('points')->insert(['id' => '65', 'name' => 'CL 18 # 11-58 Tunja Centro', 'cost_center' => 'ALMT0818', 'trade_name' => 'Tunja Centro', 'city_id' => '26']);
        DB::table('points')->insert(['id' => '66', 'name' => 'KR 4 N° 8 37', 'cost_center' => 'ALMT1128', 'trade_name' => 'Fr. Anserma', 'city_id' => '27']);
        DB::table('points')->insert(['id' => '67', 'name' => 'dirección', 'cost_center' => 'ALMT0987', 'trade_name' => 'Fr. Chinchina', 'city_id' => '28']);
        DB::table('points')->insert(['id' => '68', 'name' => 'CL 33B No 20-03 ', 'cost_center' => 'ALMT0623', 'trade_name' => 'Manizales', 'city_id' => '29']);
        DB::table('points')->insert(['id' => '69', 'name' => 'KR 11Bis 57 E 76 LC. A 2033', 'cost_center' => 'ALMT1164 ', 'trade_name' => 'Mall Plaza Manizales', 'city_id' => '29']);
        DB::table('points')->insert(['id' => '70', 'name' => 'KR 22 29 29 CC Comercial Parque Caldas LC I 17', 'cost_center' => 'ALMT1233', 'trade_name' => 'Fr. Parque Caldas', 'city_id' => '29']);
        DB::table('points')->insert(['id' => '71', 'name' => 'KR 3 Bis 21 A 14 D - 22 ', 'cost_center' => 'ALMT0671', 'trade_name' => 'Florencia', 'city_id' => '30']);
        DB::table('points')->insert(['id' => '72', 'name' => 'CL 9 8 60 BRR CENTRO', 'cost_center' => 'ALMT1246', 'trade_name' => 'Fr. Paz de ariporo', 'city_id' => '31']);
        DB::table('points')->insert(['id' => '73', 'name' => 'KR 19 no. 8-34', 'cost_center' => 'ALMT1003', 'trade_name' => 'Yopal Cra 19', 'city_id' => '32']);
        DB::table('points')->insert(['id' => '74', 'name' => 'dirección', 'cost_center' => 'ALMT0733', 'trade_name' => 'Yopal Unicentro', 'city_id' => '32']);
        DB::table('points')->insert(['id' => '75', 'name' => 'CL 9 17 67', 'cost_center' => 'ALMT0970', 'trade_name' => 'Fr. Aguazul', 'city_id' => '33']);
        DB::table('points')->insert(['id' => '76', 'name' => 'Cl 30 entre KR 28 y 29 C.C. Gran plaza alcaravan LC 074 A y B', 'cost_center' => 'ALMT1201', 'trade_name' => 'Alcaravan', 'city_id' => '32']);
        DB::table('points')->insert(['id' => '77', 'name' => 'KR 9 # 24a - norte 21 LC 125', 'cost_center' => 'ALMT0894', 'trade_name' => 'Campanario', 'city_id' => '34']);
        DB::table('points')->insert(['id' => '78', 'name' => 'CL 4 10 67 Br. Centro', 'cost_center' => 'ALMT0998', 'trade_name' => 'Fr. Santander De Quilichao', 'city_id' => '34']);
        DB::table('points')->insert(['id' => '79', 'name' => 'KR 14 5 34 BRR EL CENTRO', 'cost_center' => 'ALMT0906', 'trade_name' => 'Fr. Aguachica', 'city_id' => '35']);
        DB::table('points')->insert(['id' => '80', 'name' => 'Av. Salguero CL 31 C.C. Mayales, LC 81', 'cost_center' => 'ALMT0725', 'trade_name' => 'Mayales', 'city_id' => '36']);
        DB::table('points')->insert(['id' => '81', 'name' => 'CL 16 # 19b - 56 LC 25', 'cost_center' => 'ALMT0857', 'trade_name' => 'Megamall Valledupar', 'city_id' => '36']);
        DB::table('points')->insert(['id' => '82', 'name' => 'CL 16 B 7 48 LC 4', 'cost_center' => 'ALMT0996', 'trade_name' => 'Valledupar Centro Dos', 'city_id' => '37']);
        DB::table('points')->insert(['id' => '83', 'name' => 'Cl 25 4 40 Lc 108 Brr Pan de Yuca', 'cost_center' => 'ALMT1190', 'trade_name' => 'Fr. Quibdo', 'city_id' => '38']);
        DB::table('points')->insert(['id' => '84', 'name' => 'Cl 17 6 39 Lc 108 CC San Jose Brr. Centro', 'cost_center' => 'ALMT1016', 'trade_name' => 'Fr. Montelibano', 'city_id' => '39']);
        DB::table('points')->insert(['id' => '85', 'name' => 'CL 28 # 25B - 97 LC 1-126 Parque Comercial Guacari', 'cost_center' => 'ALMT1000', 'trade_name' => 'Guacari', 'city_id' => '40']);
        DB::table('points')->insert(['id' => '86', 'name' => 'CL 29 20-337 LC  L-0295 Nuestro Montería  ', 'cost_center' => 'ALMT0952', 'trade_name' => 'Nuestro Monteria', 'city_id' => '41']);
        DB::table('points')->insert(['id' => '87', 'name' => 'CL 33 N° 2-22 LC 1 ', 'cost_center' => 'ALMT0849', 'trade_name' => 'Montería Centro', 'city_id' => '41']);
        DB::table('points')->insert(['id' => '88', 'name' => 'CL 44  8  43 LC A 191 C.C. ALAMEDAS 2 ', 'cost_center' => 'ALMT0632', 'trade_name' => 'Monteria', 'city_id' => '41']);
        DB::table('points')->insert(['id' => '89', 'name' => 'KR 11 N° 15 - 15 LC 2', 'cost_center' => 'ALMT0924', 'trade_name' => 'Fr. Sahagun', 'city_id' => '42']);
        DB::table('points')->insert(['id' => '90', 'name' => 'CL 3 24 29 Br. Cascajal', 'cost_center' => 'ALMT0930', 'trade_name' => 'Fr. Lorica', 'city_id' => '43']);
        DB::table('points')->insert(['id' => '91', 'name' => 'CL 6 21 03 LC 1', 'cost_center' => 'ALMT0949', 'trade_name' => 'Fr. La Mesa', 'city_id' => '44']);
        DB::table('points')->insert(['id' => '92', 'name' => 'Cl 7 N 1 A 91 Este Madrid LC 04-05', 'cost_center' => 'ALMT0997', 'trade_name' => 'Casa Blanca Madrid', 'city_id' => '45']);
        DB::table('points')->insert(['id' => '93', 'name' => 'KR 7 7 43', 'cost_center' => 'ALMT0948', 'trade_name' => 'Fr. Tocancipa', 'city_id' => '46']);
        DB::table('points')->insert(['id' => '94', 'name' => 'CL 10 6 21 UBATE', 'cost_center' => 'ALMT0911', 'trade_name' => 'Fr. Ubate', 'city_id' => '47']);
        DB::table('points')->insert(['id' => '95', 'name' => ' Avenida CL 72 No 76-63', 'cost_center' => 'ALMT0991', 'trade_name' => 'Santa Helenita', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '96', 'name' => ' C.C. Gran Plaza Bosa LC 158 CL 65 sur No 78 H 51', 'cost_center' => 'ALMT0953', 'trade_name' => 'Gran Plaza Bosa', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '97', 'name' => ' KR 7 # 30B - 139 LC: 1-113', 'cost_center' => 'ALMT0891', 'trade_name' => 'Antares Soacha', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '98', 'name' => 'AV CL 9 60 70 LC 210', 'cost_center' => 'ALMT1123', 'trade_name' => 'Pradera Dos', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '99', 'name' => 'Avenida 68 # 21 – 95', 'cost_center' => 'ALMT0424', 'trade_name' => 'Avenida 68', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '100', 'name' => 'Avenida CL 72 # 68 H 27', 'cost_center' => 'ALMT0942', 'trade_name' => 'Ferias', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '101', 'name' => 'C.C Unicentro LC 2-153', 'cost_center' => 'ALMT0773', 'trade_name' => 'Unicentro', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '102', 'name' => 'C.C. Américas Outlet Factory 1 LC 1-38 Av Américas No. 62-84 Bogotá', 'cost_center' => 'ALMT0764', 'trade_name' => 'Factory', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '103', 'name' => 'C.C. Santa Fe KR. 43 No. 7 Sur – 170 LC 9100', 'cost_center' => 'ALMT0799', 'trade_name' => 'Santa Fe', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '104', 'name' => 'CL 11 No. 60-16 LC 105', 'cost_center' => 'ALMT0427', 'trade_name' => 'Pradera', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '105', 'name' => 'CL 12 # 60 - 20', 'cost_center' => 'ALMT0677', 'trade_name' => 'Hiper Americas', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '106', 'name' => 'CL 12 # 9-29 Interior 1', 'cost_center' => 'ALMT0665', 'trade_name' => 'Calle 12', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '107', 'name' => 'CL 12 N° 13 - 42', 'cost_center' => 'ALMT0615', 'trade_name' => 'San Victorino', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '108', 'name' => 'CL 164 No. 20-08', 'cost_center' => 'ALMT0408', 'trade_name' => 'Toberín', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '109', 'name' => 'CL 28 A #12-30 LC 10-29', 'cost_center' => 'ALMT0794', 'trade_name' => 'Jumbo Girardot', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '110', 'name' => 'CL 37 sur No. 78C – 09', 'cost_center' => 'ALMT0768', 'trade_name' => 'Kennedy', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '111', 'name' => 'CL 45 sur # 72 L-28', 'cost_center' => 'ALMT1212', 'trade_name' => 'Fr. Boita', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '112', 'name' => 'CL 53 N° 21 - 28 LC 102', 'cost_center' => 'ALMT0848', 'trade_name' => 'Galerias 2', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '113', 'name' => 'CL 59C sur 61-21 ', 'cost_center' => 'ALMT1188', 'trade_name' => 'Gran Plaza Ensueño', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '114', 'name' => 'CL 81#13-05 LC : L301B, L302, LC302B', 'cost_center' => 'ALMT1216', 'trade_name' => 'Atlantis', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '115', 'name' => 'CL 9 # 22 - 20', 'cost_center' => 'ALMT0865', 'trade_name' => 'San Andresito San Jose', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '116', 'name' => 'KR 100# 18-70', 'cost_center' => 'ALMT0821', 'trade_name' => 'Fontibon Carrera 100', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '117', 'name' => 'KR 13 # 41 – 36', 'cost_center' => 'ALMT0631', 'trade_name' => 'Javeriana', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '118', 'name' => 'KR 19 # 16 - 32 Sur', 'cost_center' => 'ALMT0917', 'trade_name' => 'Restrepo Dos', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '119', 'name' => 'KR 19 N° 18-54 Sur', 'cost_center' => 'ALMT0598', 'trade_name' => 'Restrepo', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '120', 'name' => 'KR 6 # 12 – 77 LC 136A', 'cost_center' => 'ALMT0416', 'trade_name' => 'Soacha centro', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '121', 'name' => 'KR 68 No. 96-50 LC 2-032', 'cost_center' => 'ALMT0797', 'trade_name' => 'Cafam Floresta', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '122', 'name' => 'KR 95A No. 49C-80 Sur', 'cost_center' => 'ALMT0791', 'trade_name' => 'Trebolis Bosa', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '123', 'name' => 'CL 127 D 58 18 C.C Bulevar Niza LC 10', 'cost_center' => 'ALMT1236', 'trade_name' => 'Fr. Bulevar Niza', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '124', 'name' => 'CL 129 50 A 24', 'cost_center' => 'ALMT0989', 'trade_name' => 'Fr. Prado', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '125', 'name' => 'CL 183 15 29 VERBENAL', 'cost_center' => 'ALMT0940', 'trade_name' => 'Fr. Verbenal', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '126', 'name' => 'CL 19 # 69-86 LC 6 ', 'cost_center' => 'ALMT1222', 'trade_name' => 'Montevideo', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '127', 'name' => 'CL 42 SUR 78A 41', 'cost_center' => 'ALMT1252', 'trade_name' => 'Fr. Palenque', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '128', 'name' => 'CL 64 # 24 - 10', 'cost_center' => 'ALMT1219', 'trade_name' => 'Fr. Siete de agosto', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '129', 'name' => 'CL 8 SUR  34 27', 'cost_center' => 'ALMT0960', 'trade_name' => 'Fr. Ciudad Montes', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '130', 'name' => 'Cll 60 No.10-78', 'cost_center' => 'ALMT0422', 'trade_name' => 'Chapinero', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '131', 'name' => 'CLL 65 SUR N 78H -51', 'cost_center' => 'ALMT1229', 'trade_name' => 'Yoi Gran Plaza Bosa', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '132', 'name' => 'KR 69-98 A 45', 'cost_center' => 'ALMT1166', 'trade_name' => 'Outlet La Floresta', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '133', 'name' => 'KR 77 A 63 F 34 LC 1', 'cost_center' => 'ALMT0928', 'trade_name' => 'Fr. Villaluz', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '134', 'name' => 'KR 78 8 46 LC 01', 'cost_center' => 'ALMT0984', 'trade_name' => 'Fr. Castilla', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '135', 'name' => 'KR 1 N° 38 53 C.C. Ventura Terreros LC 109', 'cost_center' => 'ALMT1013', 'trade_name' => 'Terreros', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '136', 'name' => 'KR 104 # 148 - 07 LC 105 y 106', 'cost_center' => 'ALMT1124', 'trade_name' => 'Plaza Imperial Dos', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '137', 'name' => 'KR 117 63 k 11', 'cost_center' => 'ALMT1213', 'trade_name' => 'Fr. Engativa', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '138', 'name' => 'KR 13 # 98 - 21 LC 1 - 65', 'cost_center' => 'ALMT1235', 'trade_name' => 'Yoi Plaza Central', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '139', 'name' => 'KR 14 75 37 S', 'cost_center' => 'ALMT0976', 'trade_name' => 'Santa Librada', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '140', 'name' => 'KR 15 N° 82-04', 'cost_center' => 'ALMT0721', 'trade_name' => 'Calle 82', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '141', 'name' => 'KR 15 N° 92-73', 'cost_center' => 'ALMT1121', 'trade_name' => 'La 93', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '142', 'name' => 'KR 53 N° 46 -20 sur ', 'cost_center' => 'ALMT0819', 'trade_name' => 'Venecia 2', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '143', 'name' => 'KR 56 4 C 18 Br. Galan', 'cost_center' => 'ALMT1172', 'trade_name' => 'Fr. Galan', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '144', 'name' => 'KR 6 N° 22C - 66 sur.', 'cost_center' => 'ALMT0815', 'trade_name' => '20 de Julio', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '145', 'name' => 'KR 65 # 11 - 90 CC Plaza Central LC N: 2-08', 'cost_center' => 'ALMT1221', 'trade_name' => 'Plaza Central 2', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '146', 'name' => 'KR 7 # 30 B - 139 CC. Gran plaza Soacha LC 163', 'cost_center' => 'ALMT1220', 'trade_name' => 'Yoi Gran Plaza Soacha', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '147', 'name' => 'KR 7# 19-56', 'cost_center' => 'ALMT1215', 'trade_name' => 'Las Nieves', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '148', 'name' => 'KR 80 N° 47 59', 'cost_center' => 'ALMT1182', 'trade_name' => 'Fr. Roma', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '149', 'name' => 'KR 88 C  56-68 Sur Barrio Bosa', 'cost_center' => 'ALMT1205', 'trade_name' => 'Fr. Bosa', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '150', 'name' => 'Diagonal 47 SUR Nº 53-10', 'cost_center' => 'ALMT0494', 'trade_name' => 'Venecia', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '151', 'name' => 'KR 104 # 148 - 07 C.C Plaza Imperial L - 1167', 'cost_center' => 'ALMT0401', 'trade_name' => 'Suba', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '152', 'name' => 'TV93 # 65 – 12', 'cost_center' => 'ALMT0423', 'trade_name' => 'Álamos', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '153', 'name' => 'TV94 N° 80d - 69', 'cost_center' => 'ALMT0850', 'trade_name' => 'Quirigua', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '154', 'name' => 'Trav 99 N° 70 A 89 C.C. Diverplaza LC 260 A', 'cost_center' => 'ALMT0834', 'trade_name' => 'Diver Plaza 2', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '155', 'name' => 'dirección', 'cost_center' => 'ALMT0614', 'trade_name' => '140', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '156', 'name' => 'KR 71d 6-94 sur plaza de las americas LC 1025', 'cost_center' => 'ALMT0825', 'trade_name' => ' Yoi Plaza de las Americas', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '157', 'name' => 'CL 12B 71D 61', 'cost_center' => 'ALMT0637', 'trade_name' => 'Bazar Alsacia', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '158', 'name' => 'Av. CL 19 No. 28 – 80 LCes B83- B85', 'cost_center' => 'ALMT0650', 'trade_name' => 'Calima', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '159', 'name' => 'Autopista Sur # 38 A Sur LC 1129', 'cost_center' => 'ALMT0419', 'trade_name' => 'Centro Mayor', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '160', 'name' => 'KR 24C No 48 Sur 50 LC 1051', 'cost_center' => 'ALMT0530', 'trade_name' => ' Ciudad Tunal', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '161', 'name' => 'AV CL 24 77 40 ', 'cost_center' => 'ALMT1266', 'trade_name' => 'Fr. Modelia', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '162', 'name' => 'KR 60 # 24 - 9 LC: L1-31 Costado Esfera.', 'cost_center' => 'ALMT0912', 'trade_name' => ' Gran Estacion', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '163', 'name' => 'Cll. 20 # 82 – 52 LC 1-103', 'cost_center' => 'ALMT0406', 'trade_name' => 'Hayuelos', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '164', 'name' => 'KR 20 N. 79-44 C.C. Heroes', 'cost_center' => 'ALMT0426', 'trade_name' => ' Héroes', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '165', 'name' => 'KR 58D # 146 - 51 LC: 320', 'cost_center' => 'ALMT0892', 'trade_name' => ' La Colina', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '166', 'name' => 'KR 62 10 47', 'cost_center' => 'ALMT1194', 'trade_name' => 'Mega Americas', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '167', 'name' => 'CL 19a No. 72 - 47 LC B -133  ', 'cost_center' => 'ALMT0951', 'trade_name' => 'Multiplaza la Felicidad', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '168', 'name' => 'Av. CL 13 # 11 - 2 LC: 3-67 / 68', 'cost_center' => 'ALMT0878', 'trade_name' => ' Plaza Central', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '169', 'name' => 'KR 71D 6-94 SUR Plaza de las Américas LC 1025 ', 'cost_center' => 'ALMT1204', 'trade_name' => ' Plaza de las Americas', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '170', 'name' => 'C.C. Portal 80 LC N-2023', 'cost_center' => 'ALMT0493', 'trade_name' => ' Portal 80', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '171', 'name' => 'KR 7 N° 32 - 35, C.C Soacha Mercurio LC 206N', 'cost_center' => 'ALMT0735', 'trade_name' => 'Soacha Mercurio', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '172', 'name' => 'Av. Ciudad De Cali # 42 B-51 Sur LC 130', 'cost_center' => 'ALMT0404', 'trade_name' => 'Tintal Outlet', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '173', 'name' => 'KR 86 No 6-37 LC 119', 'cost_center' => 'ALMT0749', 'trade_name' => 'Tintal Plaza', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '174', 'name' => 'C.C. Titan CL 80', 'cost_center' => 'ALMT0852', 'trade_name' => 'C.C. Titan Calle 80', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '175', 'name' => 'CL 81 13 05 LC 101 - 102', 'cost_center' => 'ALMT1218', 'trade_name' => 'Yoi Atlantis ', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '176', 'name' => 'KR. 59 A # 79 - 30', 'cost_center' => 'ALMT1249', 'trade_name' => 'Yoi Éxito Calle 80', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '177', 'name' => 'CL 52 13 70', 'cost_center' => 'ALMT1207', 'trade_name' => 'Yoi Éxito Chapinero ', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '178', 'name' => 'KR 72 146 B AV BOYACA ', 'cost_center' => 'ALTM1255', 'trade_name' => 'Yoi Éxito Colina', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '179', 'name' => 'KR 53 119 04', 'cost_center' => 'ALMT1243', 'trade_name' => 'Yoi Éxito Niza', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '180', 'name' => 'AUTO NORTE 173 60', 'cost_center' => 'ALMT1244', 'trade_name' => 'Yoi Éxito Norte', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '181', 'name' => 'CL 145 105B 58 ', 'cost_center' => 'ALMT1248', 'trade_name' => 'Yoi Éxito Suba', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '182', 'name' => 'KR 51 59 C SUR 93 LC 159', 'cost_center' => 'ALMT1198', 'trade_name' => 'Yoi Gran Plaza Ensueño', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '183', 'name' => 'KR 59A 79 30', 'cost_center' => 'ALMT1234', 'trade_name' => 'Yoi Portal 80', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '184', 'name' => 'CL 164 22 42', 'cost_center' => 'ALMT1197', 'trade_name' => 'Yoi Toberin', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '185', 'name' => 'CL 4 6 37', 'cost_center' => 'ALMT0920', 'trade_name' => 'Fr. Cajica', 'city_id' => '49']);
        DB::table('points')->insert(['id' => '186', 'name' => 'Av. Pradilla 900este LC: 119B', 'cost_center' => 'ALMT0847', 'trade_name' => 'Centro Chia', 'city_id' => '50']);
        DB::table('points')->insert(['id' => '187', 'name' => 'KR 11 # 12 20 LC: 102', 'cost_center' => 'ALMT0788', 'trade_name' => 'Centro Chia Dos', 'city_id' => '50']);
        DB::table('points')->insert(['id' => '188', 'name' => 'CL 10 No: 11 36 LC 106 107 C.C La Libertad', 'cost_center' => 'ALMT0851', 'trade_name' => 'Chia la Libertad', 'city_id' => '50']);
        DB::table('points')->insert(['id' => '189', 'name' => 'KR 4 No 4 84 Barrio La Castellana', 'cost_center' => 'ALMT1015', 'trade_name' => 'Fr. Mesitas', 'city_id' => '51']);
        DB::table('points')->insert(['id' => '190', 'name' => 'KR 4 6 25', 'cost_center' => 'ALMT0908', 'trade_name' => 'Fr. Facatativa', 'city_id' => '52']);
        DB::table('points')->insert(['id' => '191', 'name' => 'CL 15#12-59 /63', 'cost_center' => 'ALMT0644', 'trade_name' => 'Funza', 'city_id' => '53']);
        DB::table('points')->insert(['id' => '192', 'name' => 'CL 8 Avda de las palmas # 6 - 61 Centro', 'cost_center' => 'ALMT0816', 'trade_name' => 'Fusagasuga', 'city_id' => '54']);
        DB::table('points')->insert(['id' => '193', 'name' => 'KR 10 # 14-75 C.C Pasaje Real LC 3 y 4', 'cost_center' => 'ALMT1193', 'trade_name' => 'Girardot Cra 10', 'city_id' => '55']);
        DB::table('points')->insert(['id' => '194', 'name' => ' CL 5 # 6-52 BRR Centro', 'cost_center' => 'ALMT1206', 'trade_name' => 'Villeta', 'city_id' => '56']);
        DB::table('points')->insert(['id' => '195', 'name' => 'KR 10 Nº 4-64 LC 2', 'cost_center' => 'ALMT0645', 'trade_name' => 'Zipaquira', 'city_id' => '57']);
        DB::table('points')->insert(['id' => '196', 'name' => 'Cl 8 # 22-104 Centro ', 'cost_center' => 'ALMT1024', 'trade_name' => 'Fr. San Jose del Guaviare', 'city_id' => '58']);
        DB::table('points')->insert(['id' => '197', 'name' => 'CL 12 9 09 BRR CENTRO', 'cost_center' => 'ALMT1217', 'trade_name' => 'Fr. Maicao', 'city_id' => '59']);
        DB::table('points')->insert(['id' => '198', 'name' => 'CL 15 No 18-274 De Riohacha - Guajira LC 108', 'cost_center' => 'ALMT0831', 'trade_name' => 'Viva Guajira', 'city_id' => '60']);
        DB::table('points')->insert(['id' => '199', 'name' => 'CL 12 # 11-40 LC  1', 'cost_center' => 'ALMT1157', 'trade_name' => 'Fr. Cienaga', 'city_id' => '61']);
        DB::table('points')->insert(['id' => '200', 'name' => 'CL 7 4 61', 'cost_center' => 'ALMT0999', 'trade_name' => 'Fr. El Banco Magdalena', 'city_id' => '62']);
        DB::table('points')->insert(['id' => '201', 'name' => 'CL 29 # 15 - 100 C.C. Ocean Mall LC L2-51 Y 2-52', 'cost_center' => 'ALMT0584', 'trade_name' => 'Santa Marta', 'city_id' => '63']);
        DB::table('points')->insert(['id' => '202', 'name' => 'KR 4 No 11a - 19 LC 104', 'cost_center' => 'ALMT0860', 'trade_name' => 'Arrecife', 'city_id' => '63']);
        DB::table('points')->insert(['id' => '203', 'name' => 'Km 14 Via Cienaga Troncal del Caribe Sector Bello Horizonte LC: 1 -21', 'cost_center' => 'ALMT0726', 'trade_name' => 'Zazue', 'city_id' => '63']);
        DB::table('points')->insert(['id' => '204', 'name' => 'KR 17 15 52', 'cost_center' => 'ALMT0873', 'trade_name' => 'Fr. Acacias', 'city_id' => '64']);
        DB::table('points')->insert(['id' => '205', 'name' => 'KR 14 # 17 - 18', 'cost_center' => 'ALMT0813', 'trade_name' => 'Granada', 'city_id' => '65']);
        DB::table('points')->insert(['id' => '206', 'name' => 'KR 7A 4 80 BRR SANTANDER', 'cost_center' => 'ALMT0890', 'trade_name' => 'Puerto Lopez (Janet Boutique)', 'city_id' => '66']);
        DB::table('points')->insert(['id' => '207', 'name' => 'AV 40 26c 10 LC 204 B. Nuevo Maizaro', 'cost_center' => 'ALMT0872', 'trade_name' => 'Unicentro V/cio', 'city_id' => '67']);
        DB::table('points')->insert(['id' => '208', 'name' => 'CL 7 N 45-185 LC 152 CC Viva Villavicencio', 'cost_center' => 'ALMT0767', 'trade_name' => 'Viva Villavicencio', 'city_id' => '67']);
        DB::table('points')->insert(['id' => '209', 'name' => 'KR 22 No 8-285 C.C. Unico LC 32.', 'cost_center' => 'ALMT0668', 'trade_name' => 'Villavicencio', 'city_id' => '67']);
        DB::table('points')->insert(['id' => '210', 'name' => 'KR 30 36 76', 'cost_center' => 'ALMT0943', 'trade_name' => 'Villavicencio cra 30', 'city_id' => '67']);
        DB::table('points')->insert(['id' => '211', 'name' => 'CL 24 N° 6 – 120 C.C Gran Plaza LC 118     ', 'cost_center' => 'ALMT0785', 'trade_name' => 'Ipiales', 'city_id' => '68']);
        DB::table('points')->insert(['id' => '212', 'name' => 'KR 6 # 13-87', 'cost_center' => 'ALMT1159', 'trade_name' => 'Ipiales Centro', 'city_id' => '68']);
        DB::table('points')->insert(['id' => '213', 'name' => 'dirección', 'cost_center' => 'ALMT1165', 'trade_name' => 'Ipiales Centro Dos', 'city_id' => '68']);
        DB::table('points')->insert(['id' => '214', 'name' => 'CL 24 18 06', 'cost_center' => 'ALMT1240', 'trade_name' => 'Plaza nariño', 'city_id' => '68']);
        DB::table('points')->insert(['id' => '215', 'name' => 'dirección', 'cost_center' => 'ALMT0820', 'trade_name' => 'Pasto Calle 18', 'city_id' => '69']);
        DB::table('points')->insert(['id' => '216', 'name' => 'dirección', 'cost_center' => 'ALMT0611', 'trade_name' => 'Pasto Único', 'city_id' => '69']);
        DB::table('points')->insert(['id' => '217', 'name' => 'dirección', 'cost_center' => 'ALMT1027', 'trade_name' => 'Fr. San Andres de Tumaco', 'city_id' => '70']);
        DB::table('points')->insert(['id' => '218', 'name' => 'CL 17 No. 14-23', 'cost_center' => 'ALMT1018', 'trade_name' => 'Fr. Tuquerres', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '219', 'name' => 'KR 10 7 32', 'cost_center' => 'ALMT0965', 'trade_name' => 'Fr. Garzon', 'city_id' => '72']);
        DB::table('points')->insert(['id' => '220', 'name' => 'CL 6 # 3 - 56', 'cost_center' => 'ALMT1161', 'trade_name' => 'Fr. La plata', 'city_id' => '73']);
        DB::table('points')->insert(['id' => '221', 'name' => 'KR. 15 Sur No. 19a - 01 LC 183', 'cost_center' => 'ALMT0599', 'trade_name' => 'Pitalito', 'city_id' => '74']);
        DB::table('points')->insert(['id' => '222', 'name' => 'C.C. UNICO. CL 64 #1d 140 contiguo al aeropuerto LC 29', 'cost_center' => 'ALMT0836', 'trade_name' => 'Neiva Unico', 'city_id' => '75']);
        DB::table('points')->insert(['id' => '223', 'name' => 'CL 8 # 48 - 105 Sector Ipanema', 'cost_center' => 'ALMT0856', 'trade_name' => 'Santa Lucia', 'city_id' => '75']);
        DB::table('points')->insert(['id' => '224', 'name' => 'KR 8A No 38 - 42 (C.C. San Pedro Plaza) LC 283', 'cost_center' => 'ALMT0579', 'trade_name' => 'Neiva', 'city_id' => '75']);
        DB::table('points')->insert(['id' => '225', 'name' => 'CL 11 # 34 - 78 LC: 151', 'cost_center' => 'ALMT0415', 'trade_name' => 'Pasto', 'city_id' => '69']);
        DB::table('points')->insert(['id' => '226', 'name' => 'KR 13 11 40 Br. El Centro', 'cost_center' => 'ALMT0974', 'trade_name' => 'Fr. Ocaña', 'city_id' => '76']);
        DB::table('points')->insert(['id' => '227', 'name' => 'KR 5 8 02/14 LC 1 y 2 Barrio Centro Pamplona', 'cost_center' => 'ALMT1189', 'trade_name' => 'Fr. Pamplona', 'city_id' => '77']);
        DB::table('points')->insert(['id' => '228', 'name' => 'C.C. Ventura Plaza Diagonal Santander CL 10 y 11 LC 1-24 Sector quinta velez', 'cost_center' => 'ALMT0824', 'trade_name' => 'Ventura', 'city_id' => '78']);
        DB::table('points')->insert(['id' => '229', 'name' => 'CL 12 # 5-23 Centro', 'cost_center' => 'ALMT0620', 'trade_name' => 'Cucuta Calle 12', 'city_id' => '78']);
        DB::table('points')->insert(['id' => '230', 'name' => 'AV. Libertadores AV. 1 CL 20 N. C.C.Unicentro LC 1-115 Cucuta', 'cost_center' => 'ALMT0407', 'trade_name' => 'Cucuta', 'city_id' => '78']);
        DB::table('points')->insert(['id' => '231', 'name' => 'C.C. Jardín Plaza LC L-74 Anillo Vial Oriental Vía La Gasapa', 'cost_center' => 'ALMT1203', 'trade_name' => ' Jardin Plaza', 'city_id' => '78']);
        DB::table('points')->insert(['id' => '232', 'name' => 'Diagonal 56 #18a - 88 LC 214', 'cost_center' => 'ALMT0944', 'trade_name' => 'San silvestre', 'city_id' => '79']);
        DB::table('points')->insert(['id' => '233', 'name' => 'KR 18 No. 11 - 91', 'cost_center' => 'ALMT1187', 'trade_name' => 'Fr. Puerto Asis', 'city_id' => '80']);
        DB::table('points')->insert(['id' => '234', 'name' => 'KR 17 # 18-19 Centro', 'cost_center' => 'ALMT0490', 'trade_name' => 'Armenia', 'city_id' => '81']);
        DB::table('points')->insert(['id' => '235', 'name' => 'CL 19 N # 12-60 LC No 3-13 N3-14 C.C Portal Del Quindio', 'cost_center' => 'ALMT0588', 'trade_name' => 'Quindio', 'city_id' => '81']);
        DB::table('points')->insert(['id' => '236', 'name' => 'cc portal del quindio LC 4 piso 1', 'cost_center' => 'ALMT1200', 'trade_name' => 'Quindio 2', 'city_id' => '81']);
        DB::table('points')->insert(['id' => '237', 'name' => 'C.C. PORTAL DE QUINDIO NIVEL 3 LC 13 14 15', 'cost_center' => 'ALTMT1211', 'trade_name' => 'Yoi Portal Quindio', 'city_id' => '81']);
        DB::table('points')->insert(['id' => '238', 'name' => 'KR 25 32 30 ', 'cost_center' => 'ALMT0938', 'trade_name' => 'Fr. Calarca', 'city_id' => '82']);
        DB::table('points')->insert(['id' => '239', 'name' => 'KR 6 18 32', 'cost_center' => 'ALMT1005', 'trade_name' => 'Fr. Quimbaya', 'city_id' => '83']);
        DB::table('points')->insert(['id' => '240', 'name' => 'dirección', 'cost_center' => 'ALMT0939', 'trade_name' => 'Fr. Santa Rosa de Cabal', 'city_id' => '84']);
        DB::table('points')->insert(['id' => '241', 'name' => 'Av circunvalar No 5-20 C.C. Arboleda LC 132A ​', 'cost_center' => 'ALMT0777', 'trade_name' => 'Arboleda', 'city_id' => '85']);
        DB::table('points')->insert(['id' => '242', 'name' => 'Av. simón  Bolívar KR 16 No 36-98 CC El progreso LC 26-27', 'cost_center' => 'ALMT0583', 'trade_name' => 'Progreso', 'city_id' => '85']);
        DB::table('points')->insert(['id' => '243', 'name' => 'Avda 30 de Agosto # 68-125 LC B-02 C.C. Unicentro', 'cost_center' => 'ALMT0412', 'trade_name' => 'Pereira', 'city_id' => '85']);
        DB::table('points')->insert(['id' => '244', 'name' => 'CL 17 No 19 - 230 LC 19 C.C. La 14 ', 'cost_center' => 'ALMT0829', 'trade_name' => 'Pereira Calima', 'city_id' => '85']);
        DB::table('points')->insert(['id' => '245', 'name' => 'KR 6 No 18-29', 'cost_center' => 'ALMT0765', 'trade_name' => 'Pereira Centro Dos', 'city_id' => '85']);
        DB::table('points')->insert(['id' => '246', 'name' => 'CL 69 25 08 LC 102 ', 'cost_center' => 'ALMT0971', 'trade_name' => 'Fr. Pereira Cuba', 'city_id' => '85']);
        DB::table('points')->insert(['id' => '247', 'name' => 'KR 9 17 23', 'cost_center' => 'ALMT0862', 'trade_name' => 'Pereira Cr 9', 'city_id' => '85']);
        DB::table('points')->insert(['id' => '248', 'name' => 'KRa 16 Cl 24 Esquina Av simon bolivar LC 32, C.C. Unico Dosquebradas  ', 'cost_center' => 'ALMT1109 ', 'trade_name' => 'Dos Quebradas Unico', 'city_id' => '85']);
        DB::table('points')->insert(['id' => '249', 'name' => '  AV LIBERTADORES CC CAPRI LC 32 ESQ', 'cost_center' => 'ALMT0947', 'trade_name' => 'Fr. San Andres', 'city_id' => '86']);
        DB::table('points')->insert(['id' => '250', 'name' => 'KR 17 49 11 BRR COLOMBIA', 'cost_center' => 'ALMT0886', 'trade_name' => 'Fr. B/bermeja', 'city_id' => '87']);
        DB::table('points')->insert(['id' => '251', 'name' => 'CL 7 8 40', 'cost_center' => 'ALMT0905', 'trade_name' => 'Fr. Barbosa', 'city_id' => '88']);
        DB::table('points')->insert(['id' => '252', 'name' => 'CL 6 # 5-33 B. Centro', 'cost_center' => 'ALMT1129', 'trade_name' => 'Fr. Cimitarra', 'city_id' => '89']);
        DB::table('points')->insert(['id' => '253', 'name' => 'Cl 41 22 80 Br El Poblado', 'cost_center' => 'ALMT0935', 'trade_name' => 'Fr. Giron', 'city_id' => '90']);
        DB::table('points')->insert(['id' => '254', 'name' => 'dirección', 'cost_center' => 'ALMT0907', 'trade_name' => 'Fr. San Gil (Saroga)', 'city_id' => '91']);
        DB::table('points')->insert(['id' => '255', 'name' => 'AV Quebrada Seca N° 33A-100 LC  20 y 21 Piso 2', 'cost_center' => 'ALMT0826', 'trade_name' => 'Megamall', 'city_id' => '92']);
        DB::table('points')->insert(['id' => '256', 'name' => 'Av Samanes No 9-140 C.C. AKRópolis L1-56 y 1-57', 'cost_center' => 'ALMT0759', 'trade_name' => 'Acropolis', 'city_id' => '92']);
        DB::table('points')->insert(['id' => '257', 'name' => 'CL 20 # 21-14 ', 'cost_center' => 'ALMT1130', 'trade_name' => 'Fr. San francisco', 'city_id' => '92']);
        DB::table('points')->insert(['id' => '258', 'name' => 'CL 41 N° 34-16 LC 2 y 3 Barrio El Prado', 'cost_center' => 'ALMT0626', 'trade_name' => 'Cabecera', 'city_id' => '92']);
        DB::table('points')->insert(['id' => '259', 'name' => 'KR 14 # 37-39 Centro', 'cost_center' => 'ALMT0627', 'trade_name' => 'Bucaramanga', 'city_id' => '92']);
        DB::table('points')->insert(['id' => '260', 'name' => 'KR 18 N° 36 - 11', 'cost_center' => 'ALMT0842', 'trade_name' => 'Bucaramanga Calle 36', 'city_id' => '92']);
        DB::table('points')->insert(['id' => '261', 'name' => 'KR 27 # 29-145 CC Parque Caracoli LC 336', 'cost_center' => 'ALMT0669', 'trade_name' => 'Caracoli', 'city_id' => '92']);
        DB::table('points')->insert(['id' => '262', 'name' => 'KR 33 51 119 LC 101 102 103', 'cost_center' => 'ALMT0918', 'trade_name' => 'Cosmocentro', 'city_id' => '92']);
        DB::table('points')->insert(['id' => '263', 'name' => 'Trv 93 # 34 - 99 LC: 384A', 'cost_center' => 'ALMT0863', 'trade_name' => 'Cacique', 'city_id' => '92']);
        DB::table('points')->insert(['id' => '264', 'name' => 'KR 15 # 3AN - 40 C.C LC 242', 'cost_center' => 'ALMT0782', 'trade_name' => 'De la cuesta', 'city_id' => '93']);
        DB::table('points')->insert(['id' => '265', 'name' => 'KR 8  # 8-90 LC 1 centro', 'cost_center' => 'ALMT1227', 'trade_name' => 'Fr. Piedecuesta', 'city_id' => '93']);
        DB::table('points')->insert(['id' => '266', 'name' => 'KR 9 # 8 - 65', 'cost_center' => 'ALMT1185', 'trade_name' => 'Fr. Chaparral', 'city_id' => '94']);
        DB::table('points')->insert(['id' => '267', 'name' => 'KR 5 11 02 LC 2', 'cost_center' => 'ALMT0875', 'trade_name' => 'Fr. Espinal', 'city_id' => '95']);
        DB::table('points')->insert(['id' => '268', 'name' => 'AV Kennedy, CL 34 CC. Unicentro LC 2 - 32', 'cost_center' => 'ALMT0786', 'trade_name' => 'Girardot', 'city_id' => '96']);
        DB::table('points')->insert(['id' => '269', 'name' => 'CL 9 9 116 LC 2 AV CENTENARIO', 'cost_center' => 'ALMT1208', 'trade_name' => 'Fr. Honda', 'city_id' => '97']);
        DB::table('points')->insert(['id' => '270', 'name' => 'AV 15 # 3a-21', 'cost_center' => 'ALMT0778', 'trade_name' => 'Ibague Centro', 'city_id' => '98']);
        DB::table('points')->insert(['id' => '271', 'name' => 'C.C. Multicentro  LC 234 KR 5 61 41', 'cost_center' => 'ALMT0995', 'trade_name' => 'Multicentro Ibague', 'city_id' => '98']);
        DB::table('points')->insert(['id' => '272', 'name' => 'Cll 60 12-224 LC 202 CC La Estación', 'cost_center' => 'ALMT0743', 'trade_name' => 'Ibague', 'city_id' => '98']);
        DB::table('points')->insert(['id' => '273', 'name' => 'KR 57 60K 08 C.C ACQUA POER CENTRAL LC 203 204', 'cost_center' => 'ALMT0779', 'trade_name' => 'Ibague', 'city_id' => '98']);
        DB::table('points')->insert(['id' => '274', 'name' => 'KR 5 5 71 LC 1', 'cost_center' => 'ALMT0980', 'trade_name' => 'Fr. Mariquita', 'city_id' => '99']);
        DB::table('points')->insert(['id' => '275', 'name' => 'KR 24 7 54 LC 5 ', 'cost_center' => 'ALMT0929', 'trade_name' => 'Fr. Melgar', 'city_id' => '100']);
        DB::table('points')->insert(['id' => '276', 'name' => 'CL 3 N° 3 - 92', 'cost_center' => 'ALMT0922', 'trade_name' => 'Fr. Buenaventura', 'city_id' => '101']);
        DB::table('points')->insert(['id' => '277', 'name' => 'KR 14 6 20 Los Portales', 'cost_center' => 'ALMT0925', 'trade_name' => 'Fr. Buga', 'city_id' => '102']);
        DB::table('points')->insert(['id' => '278', 'name' => 'KR 16 N° 9 - 39', 'cost_center' => 'ALMT1150', 'trade_name' => 'Fr. Caicedonia', 'city_id' => '103']);
        DB::table('points')->insert(['id' => '279', 'name' => ' CL 5 No. 68-03 LC 134', 'cost_center' => 'ALMT0414', 'trade_name' => 'Cali Limonar', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '280', 'name' => 'CL 13 23d-29', 'cost_center' => 'ALMT1199', 'trade_name' => 'Cali Luna', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '281', 'name' => 'CL 52 N° 3 - 80 CC Unico Dos LC 509', 'cost_center' => 'ALMT0832', 'trade_name' => 'Cali Unico Dos', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '282', 'name' => 'CL 52# 3-80 C.C. unico 435', 'cost_center' => 'ALMT0413', 'trade_name' => 'Cali Unico', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '283', 'name' => 'CL 9A No 32A-16 Barrio el cedro cc centro sur', 'cost_center' => 'ALMT0714', 'trade_name' => 'Cali Sur Plaza', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '284', 'name' => 'KR 1 CL 70 C.C la 14 de calima Sótano', 'cost_center' => 'ALMT0841', 'trade_name' => 'Calima La 14', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '285', 'name' => 'CL 5 50 103 LC 2G', 'cost_center' => 'ALMT1175', 'trade_name' => 'Cosmocentro Cali', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '286', 'name' => 'C.C.  Chipichape LC 213 Bodega 2 CL 38 No 6 Norte ', 'cost_center' => 'ALMT0973', 'trade_name' => 'Chipichape', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '287', 'name' => 'CL 13 43 25 P 1', 'cost_center' => 'ALMT0889', 'trade_name' => 'Fr. Cali Pasoancho', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '288', 'name' => 'Cl 9A 3 # 48-51 LC 1-71 LC 1-71', 'cost_center' => 'ALMT0729', 'trade_name' => 'Palmetto Plaza', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '289', 'name' => 'KR 8 10 60', 'cost_center' => 'ALMT0879', 'trade_name' => 'Fr. Cali (Comertexco)', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '290', 'name' => 'dirección', 'cost_center' => 'ALMT0760', 'trade_name' => 'Cali Centro 2', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '291', 'name' => 'Av 5 norte # 24-N-68  LC 17 (la pasarela)', 'cost_center' => 'ALMT0817', 'trade_name' => ' Norte Cali', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '292', 'name' => 'CL 47 3 125 LC 435', 'cost_center' => 'ALMT1237', 'trade_name' => 'Yoi Cali Unico ', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '293', 'name' => 'KR 7 8-58 Br. Maria Auxiliadora Candelaria  ', 'cost_center' => 'ALMT1008', 'trade_name' => 'Fr. Candelaria', 'city_id' => '105']);
        DB::table('points')->insert(['id' => '294', 'name' => 'C.C SANTIAGO PLAZA LC 35', 'cost_center' => 'ALMT0888', 'trade_name' => 'Fr. Cartago', 'city_id' => '106']);
        DB::table('points')->insert(['id' => '295', 'name' => 'dirección', 'cost_center' => 'ALMT1192', 'trade_name' => 'Fr. El Cerrito', 'city_id' => '107']);
        DB::table('points')->insert(['id' => '296', 'name' => 'KR 11 # 11-34 B. Juan de Ampudia', 'cost_center' => 'ALMT1127', 'trade_name' => 'Fr. Jamundi', 'city_id' => '108']);
        DB::table('points')->insert(['id' => '297', 'name' => 'KR 15 16 43 LC 1', 'cost_center' => 'ALMT1010', 'trade_name' => 'Fr. La Union ', 'city_id' => '109']);
        DB::table('points')->insert(['id' => '298', 'name' => 'KR 26 N° 29 - 14 LC 26', 'cost_center' => 'ALMT0927', 'trade_name' => 'Fr. Palmira', 'city_id' => '110']);
        DB::table('points')->insert(['id' => '299', 'name' => 'dirección', 'cost_center' => 'ALMT1002', 'trade_name' => 'Llano Grande', 'city_id' => '110']);
        DB::table('points')->insert(['id' => '300', 'name' => 'dirección', 'cost_center' => 'ALMT0736', 'trade_name' => 'Palmira Unicentro', 'city_id' => '110']);
        DB::table('points')->insert(['id' => '301', 'name' => 'CL 9 # 5 - 71 B. Centro', 'cost_center' => 'ALMT1183', 'trade_name' => 'Fr. Roldanillo', 'city_id' => '111']);
        DB::table('points')->insert(['id' => '302', 'name' => 'dirección', 'cost_center' => 'ALTM0979', 'trade_name' => 'Fr. Sevilla', 'city_id' => '112']);
        DB::table('points')->insert(['id' => '303', 'name' => 'KR 25 # 27-63 Frente al C.C. Plenocentro', 'cost_center' => 'ALMT0652', 'trade_name' => 'Tulua', 'city_id' => '113']);
        DB::table('points')->insert(['id' => '304', 'name' => 'KR 5 #  14- 100 C.C Unico Outlet LC 06', 'cost_center' => 'ALMT0653', 'trade_name' => 'Yumbo', 'city_id' => '114']);
        DB::table('points')->insert(['id' => '305', 'name' => 'KR 11 8 87', 'cost_center' => 'ALMT0978', 'trade_name' => 'Fr. Zarzal', 'city_id' => '115']);

    }
}
