<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PointsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('points')->insert(['id' => '1', 'name' => 'Suba', 'cost_center' => 'ALMT0401', 'trade_name' => 'Kr 104 # 148 07 C.C Plaza Imperial L 1167', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '2', 'name' => 'Tunja', 'cost_center' => 'ALMT0402', 'trade_name' => 'AV Universitario No 39 77 C.C Unicentro Tunja Local 1019', 'city_id' => '116']);
        DB::table('points')->insert(['id' => '3', 'name' => 'Tintal Outlet', 'cost_center' => 'ALMT0404', 'trade_name' => 'Av. Ciudad De Cali # 42 B 51 Sur Local 130', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '4', 'name' => 'Premium Plaza', 'cost_center' => 'ALMT0405', 'trade_name' => 'Premiun Plaza Local 2302', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '5', 'name' => 'Hayuelos', 'cost_center' => 'ALMT0406', 'trade_name' => 'Cll. 20 # 82 – 52 Local 1 103', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '6', 'name' => 'Cucuta', 'cost_center' => 'ALMT0407', 'trade_name' => 'AV. Libertadores AV. 1 CL 20 N. C.C.Unicentro LC 1 115 Cucuta', 'city_id' => '33']);
        DB::table('points')->insert(['id' => '7', 'name' => 'Toberín', 'cost_center' => 'ALMT0408', 'trade_name' => 'Calle 164 No. 20 8', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '8', 'name' => 'Cartagena', 'cost_center' => 'ALMT0409', 'trade_name' => 'Caribe Plaza Local N° 79 80. Barrio la Popa', 'city_id' => '23']);
        DB::table('points')->insert(['id' => '9', 'name' => 'Único Barranquilla', 'cost_center' => 'ALMT0410', 'trade_name' => 'Cra 41D No 74 87 Único L 107', 'city_id' => '10']);
        DB::table('points')->insert(['id' => '10', 'name' => 'Único', 'cost_center' => 'ALMT0411', 'trade_name' => 'Cra 41D No 74 87 Único L 73', 'city_id' => '10']);
        DB::table('points')->insert(['id' => '11', 'name' => 'Pereira', 'cost_center' => 'ALMT0412', 'trade_name' => 'Avda 30 de Agosto # 68 125 Local B 02 Centro Comercial Unicentro', 'city_id' => '82']);
        DB::table('points')->insert(['id' => '12', 'name' => 'Cali Limonar', 'cost_center' => 'ALMT0414', 'trade_name' => 'Calle 5 No. 68 03 local 134', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '13', 'name' => 'Pasto', 'cost_center' => 'ALMT0415', 'trade_name' => 'Calle 11 # 34 78 Local: 151', 'city_id' => '80']);
        DB::table('points')->insert(['id' => '14', 'name' => 'Soacha centro', 'cost_center' => 'ALMT0416', 'trade_name' => 'Carrera 6 # 12 – 77 Local 136A', 'city_id' => '110']);
        DB::table('points')->insert(['id' => '15', 'name' => 'Centro Mayor', 'cost_center' => 'ALMT0419', 'trade_name' => 'Autopista Sur # 38 A Sur Local 1129', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '16', 'name' => 'La 33', 'cost_center' => 'ALMT0420', 'trade_name' => 'Calle 37 No. 50 – 36', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '17', 'name' => 'Santa Fe', 'cost_center' => 'ALMT0421', 'trade_name' => 'Santa Fe Cra. 43 No. 7 Sur – 170 Local 9100', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '18', 'name' => 'Chapinero', 'cost_center' => 'ALMT0422', 'trade_name' => 'Cll 60 No.10 78', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '19', 'name' => 'Álamos', 'cost_center' => 'ALMT0423', 'trade_name' => 'Transversal 93 # 65 – 12', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '20', 'name' => 'Avenida 68', 'cost_center' => 'ALMT0424', 'trade_name' => 'Avenida 68 # 21 – 95', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '21', 'name' => 'Héroes', 'cost_center' => 'ALMT0426', 'trade_name' => 'Cra 20 N. 79 44 Heroes', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '22', 'name' => 'Pradera', 'cost_center' => 'ALMT0427', 'trade_name' => 'Calle 11 No. 60 16 Local 105', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '23', 'name' => 'Armenia', 'cost_center' => 'ALMT0490', 'trade_name' => 'Cra 17 # 18 19 Centro', 'city_id' => '7']);
        DB::table('points')->insert(['id' => '24', 'name' => 'Junin', 'cost_center' => 'ALMT0492', 'trade_name' => 'Cll 53 No. 47 52', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '25', 'name' => 'Portal 80', 'cost_center' => 'ALMT0493', 'trade_name' => 'Portal 80 Local N 2023', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '26', 'name' => 'Venecia', 'cost_center' => 'ALMT0494', 'trade_name' => 'Diagonal 47 SUR Nº 53 10', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '27', 'name' => 'Ciudad Tunal', 'cost_center' => 'ALMT0530', 'trade_name' => 'Cra 24C No 48 Sur 50 Local 1051', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '28', 'name' => 'Metropolitano', 'cost_center' => 'ALMT0570', 'trade_name' => 'Cra 28 No 58 148 Local 203', 'city_id' => '10']);
        DB::table('points')->insert(['id' => '29', 'name' => 'Neiva', 'cost_center' => 'ALMT0579', 'trade_name' => 'Carrera 8A No 38 42 (San Pedro Plaza) Local 283', 'city_id' => '76']);
        DB::table('points')->insert(['id' => '30', 'name' => 'Progreso', 'cost_center' => 'ALMT0583', 'trade_name' => 'Av. simón Bolívar cra 16 No 36 98 CC El progreso local 26 27', 'city_id' => '34']);
        DB::table('points')->insert(['id' => '31', 'name' => 'Santa Marta', 'cost_center' => 'ALMT0584', 'trade_name' => 'Calle 29 # 15 100 Ocean Mall Local L2 51 Y 2 52', 'city_id' => '103']);
        DB::table('points')->insert(['id' => '32', 'name' => 'Rionegro', 'cost_center' => 'ALMT0586', 'trade_name' => 'Carrera 48A No. 50 77 local 107', 'city_id' => '94']);
        DB::table('points')->insert(['id' => '33', 'name' => 'Quindio', 'cost_center' => 'ALMT0588', 'trade_name' => 'Calle 19 N # 12 60 Local No 3 13 N3 14 C.C Portal Del Quindio', 'city_id' => '7']);
        DB::table('points')->insert(['id' => '34', 'name' => 'Restrepo', 'cost_center' => 'ALMT0598', 'trade_name' => 'Carrera 19 N° 18 54 Sur', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '35', 'name' => 'Pitalito', 'cost_center' => 'ALMT0599', 'trade_name' => 'Cra. 15 Sur No. 19a 01 Local 183', 'city_id' => '85']);
        DB::table('points')->insert(['id' => '36', 'name' => 'Bello', 'cost_center' => 'ALMT0603', 'trade_name' => 'Calle 51 No. 51 19 Barrio Perez', 'city_id' => '11']);
        DB::table('points')->insert(['id' => '37', 'name' => 'Pasto Único', 'cost_center' => 'ALMT0611', 'trade_name' => 'Calle 22 # 6 61 Local: 026 B. Pucalpa 2', 'city_id' => '80']);
        DB::table('points')->insert(['id' => '38', 'name' => '140', 'cost_center' => 'ALMT0614', 'trade_name' => 'Carrera 15 N° 140 – 05', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '39', 'name' => 'San Victorino', 'cost_center' => 'ALMT0615', 'trade_name' => 'Calle 12 N° 13 42', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '40', 'name' => 'Cucuta Calle 12', 'cost_center' => 'ALMT0620', 'trade_name' => 'Calle 12 # 5 23 Centro', 'city_id' => '33']);
        DB::table('points')->insert(['id' => '41', 'name' => 'Manizales', 'cost_center' => 'ALMT0623', 'trade_name' => 'Calle 33B No 20 03', 'city_id' => '68']);
        DB::table('points')->insert(['id' => '42', 'name' => 'Cabecera', 'cost_center' => 'ALMT0626', 'trade_name' => 'Calle 41 N° 34 16 Local 2 y 3 Barrio El Prado', 'city_id' => '13']);
        DB::table('points')->insert(['id' => '43', 'name' => 'Bucaramanga', 'cost_center' => 'ALMT0627', 'trade_name' => 'Carrera 14 # 37 39 Centro', 'city_id' => '13']);
        DB::table('points')->insert(['id' => '44', 'name' => 'Barranquilla calle 72', 'cost_center' => 'ALMT0628', 'trade_name' => 'Calle 72 # 52 36 Local 9', 'city_id' => '10']);
        DB::table('points')->insert(['id' => '45', 'name' => 'Javeriana', 'cost_center' => 'ALMT0631', 'trade_name' => 'Carrera 13 # 41 – 36', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '46', 'name' => 'Montería', 'cost_center' => 'ALMT0632', 'trade_name' => 'Calle 44 N° 8 43 Local a 191 Alamedas 2', 'city_id' => '75']);
        DB::table('points')->insert(['id' => '47', 'name' => 'Bazar Alsacia', 'cost_center' => 'ALMT0637', 'trade_name' => 'Calle 12B No 71D – 61', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '48', 'name' => 'Funza', 'cost_center' => 'ALMT0644', 'trade_name' => 'Calle 15#12 59 /63', 'city_id' => '45']);
        DB::table('points')->insert(['id' => '49', 'name' => 'Zipaquira', 'cost_center' => 'ALMT0645', 'trade_name' => 'Cra 10 Nº 4 64 Local 2', 'city_id' => '125']);
        DB::table('points')->insert(['id' => '50', 'name' => 'El Bosque', 'cost_center' => 'ALMT0646', 'trade_name' => 'Transversal 43. Barrio Nuevo Bosque Local 3', 'city_id' => '23']);
        DB::table('points')->insert(['id' => '51', 'name' => 'Calima', 'cost_center' => 'ALMT0650', 'trade_name' => 'Av. Calle 19 No. 28 – 80 Locales B83 B85', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '52', 'name' => 'Tulua', 'cost_center' => 'ALMT0652', 'trade_name' => 'Cra 25 # 27 63 Frente al Plenocentro', 'city_id' => '115']);
        DB::table('points')->insert(['id' => '53', 'name' => 'Yumbo', 'cost_center' => 'ALMT0653', 'trade_name' => 'Cra 5 # 14 100 C.C Unico Outlet Local 06', 'city_id' => '123']);
        DB::table('points')->insert(['id' => '54', 'name' => 'Calle 12', 'cost_center' => 'ALMT0665', 'trade_name' => 'Calle 12 # 9 29 Interior 1', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '55', 'name' => 'Villavicencio', 'cost_center' => 'ALMT0668', 'trade_name' => 'Cra 22 No 8 285 Centro Comercial Unico Local 32.', 'city_id' => '120']);
        DB::table('points')->insert(['id' => '56', 'name' => 'Caracoli', 'cost_center' => 'ALMT0669', 'trade_name' => 'Carrera 27 # 29 145 CC Parque Caracoli Local 336', 'city_id' => '44']);
        DB::table('points')->insert(['id' => '57', 'name' => 'Florencia', 'cost_center' => 'ALMT0671', 'trade_name' => 'Cra 3 Bis 21 A 14 D 22', 'city_id' => '22']);
        DB::table('points')->insert(['id' => '58', 'name' => 'Hiper Americas', 'cost_center' => 'ALMT0677', 'trade_name' => 'calle 12 # 60 20', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '59', 'name' => 'Soledad', 'cost_center' => 'ALMT0692', 'trade_name' => 'Cra 37 No 30 33 Local 154 Gran Plaza Del Sol.', 'city_id' => '112']);
        DB::table('points')->insert(['id' => '60', 'name' => 'Cali Sur Plaza', 'cost_center' => 'ALMT0714', 'trade_name' => 'calle 9A No 32A 16 Barrio el cedro cc centro sur', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '61', 'name' => 'Nao', 'cost_center' => 'ALMT0716', 'trade_name' => 'Bocagrande Carrera 2 N° 5 85 Nao Local 28', 'city_id' => '23']);
        DB::table('points')->insert(['id' => '62', 'name' => 'Calle 82', 'cost_center' => 'ALMT0721', 'trade_name' => 'Cra 15 N° 82 4', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '63', 'name' => 'Mayales', 'cost_center' => 'ALMT0725', 'trade_name' => 'Av. Salguero Calle 31 Mayales, Local 81', 'city_id' => '119']);
        DB::table('points')->insert(['id' => '64', 'name' => 'Zazue', 'cost_center' => 'ALMT0726', 'trade_name' => 'Km 14 Via Cienaga Troncal del Caribe Sector Bello Horizonte Local: 1 21', 'city_id' => '103']);
        DB::table('points')->insert(['id' => '65', 'name' => 'Palmetto Plaza', 'cost_center' => 'ALMT0729', 'trade_name' => 'Cl 9A 3 # 48 51 local 1 71 local 1 71', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '66', 'name' => 'Yopal Unicentro', 'cost_center' => 'ALMT0733', 'trade_name' => 'Av. Carrera 29 Entre Calles 14 Y 16 Local: 207', 'city_id' => '122']);
        DB::table('points')->insert(['id' => '67', 'name' => 'Soacha Mercurio', 'cost_center' => 'ALMT0735', 'trade_name' => 'Cra 7 N° 32 35, C.C Soacha Mercurio Local 206N', 'city_id' => '110']);
        DB::table('points')->insert(['id' => '68', 'name' => 'Palmira Unicentro', 'cost_center' => 'ALMT0736', 'trade_name' => 'Calle 42 entre calles 39 y 40 loc 1 51 CC Unicentro', 'city_id' => '78']);
        DB::table('points')->insert(['id' => '69', 'name' => 'San Fernando', 'cost_center' => 'ALMT0737', 'trade_name' => 'Calle 31 N° 83b 104 San Fernando, Local 121', 'city_id' => '23']);
        DB::table('points')->insert(['id' => '70', 'name' => 'Ibague', 'cost_center' => 'ALMT0743', 'trade_name' => 'Cll 60 12 224 local 202 CC La Estación', 'city_id' => '53']);
        DB::table('points')->insert(['id' => '71', 'name' => 'Tintal Plaza', 'cost_center' => 'ALMT0749', 'trade_name' => 'Cra 86 No 6 37 Local 119', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '72', 'name' => 'Acropolis', 'cost_center' => 'ALMT0759', 'trade_name' => 'Av Samanes No 9 140 Acrópolis L1 56 y 1 57', 'city_id' => '13']);
        DB::table('points')->insert(['id' => '73', 'name' => 'Cali Centro 2', 'cost_center' => 'ALMT0760', 'trade_name' => 'CL 13 7 18 Local 101E', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '74', 'name' => 'Guayabal', 'cost_center' => 'ALMT0761', 'trade_name' => 'Outlet Guayabal local 04', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '75', 'name' => 'Factory', 'cost_center' => 'ALMT0764', 'trade_name' => 'Américas Outlet Factory 1 Local 1 38 Av Américas No. 62 84 Bogotá', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '76', 'name' => 'Pereira Centro Dos', 'cost_center' => 'ALMT0765', 'trade_name' => 'Carrera 6 No 18 29', 'city_id' => '82']);
        DB::table('points')->insert(['id' => '77', 'name' => 'Viva Villavicencio', 'cost_center' => 'ALMT0767', 'trade_name' => 'Calle 7 N 45 185 Local 152 CC Viva Villavicencio', 'city_id' => '120']);
        DB::table('points')->insert(['id' => '78', 'name' => 'Kennedy', 'cost_center' => 'ALMT0768', 'trade_name' => 'Calle 37 sur No. 78C – 09', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '79', 'name' => 'Arboleda', 'cost_center' => 'ALMT0777', 'trade_name' => 'Av circunvalar No 5 20 Arboleda local 132A ​', 'city_id' => '82']);
        DB::table('points')->insert(['id' => '80', 'name' => 'Ibague Centro', 'cost_center' => 'ALMT0778', 'trade_name' => 'AV 15 # 3a 21', 'city_id' => '53']);
        DB::table('points')->insert(['id' => '81', 'name' => 'Acqua', 'cost_center' => 'ALMT0779', 'trade_name' => 'Cra 57 N° 60k 08 Acqua Power Center, Local 203 204', 'city_id' => '53']);
        DB::table('points')->insert(['id' => '82', 'name' => 'De la Cuesta', 'cost_center' => 'ALMT0782', 'trade_name' => 'Cra 15 # 3AN 40 C.C Local 242', 'city_id' => '84']);
        DB::table('points')->insert(['id' => '83', 'name' => 'San Nicolas', 'cost_center' => 'ALMT0783', 'trade_name' => 'San Nicolás Calle 43 No. 54 139 local 3307', 'city_id' => '94']);
        DB::table('points')->insert(['id' => '84', 'name' => 'Ipiales', 'cost_center' => 'ALMT0785', 'trade_name' => 'Calle 24 N° 6 – 120 C.C Gran Plaza Local 118', 'city_id' => '54']);
        DB::table('points')->insert(['id' => '85', 'name' => 'Girardot', 'cost_center' => 'ALMT0786', 'trade_name' => 'AV Kennedy, Calle 34 CC. Unicentro Local 2 32', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '86', 'name' => 'Chia la Libertad', 'cost_center' => 'ALMT0788', 'trade_name' => 'Calle 10 No: 11 36 Local 106 107 C.C La Libertad', 'city_id' => '27']);
        DB::table('points')->insert(['id' => '87', 'name' => 'Trebolis Bosa', 'cost_center' => 'ALMT0791', 'trade_name' => 'Carrera 95A No. 49C 80 Sur', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '88', 'name' => 'Jumbo Girardot', 'cost_center' => 'ALMT0792', 'trade_name' => 'Calle 28 A #12 30 Local 10 29', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '89', 'name' => 'Hayuelos Cencosud', 'cost_center' => 'ALMT0794', 'trade_name' => 'Cra 86 N° 19a 50 Jumbo local 2001 primer nivel.', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '90', 'name' => 'Villa Country', 'cost_center' => 'ALMT0796', 'trade_name' => 'CL 78 53 70 N 233', 'city_id' => '10']);
        DB::table('points')->insert(['id' => '91', 'name' => 'Cafam Floresta', 'cost_center' => 'ALMT0797', 'trade_name' => 'Carrera 68 No. 96 50 Local 2 32', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '92', 'name' => 'Santa Fe Bta', 'cost_center' => 'ALMT0799', 'trade_name' => 'C.C.Santa Fe Local 201', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '93', 'name' => 'Granada', 'cost_center' => 'ALMT0813', 'trade_name' => 'Carrera 14 # 17 18', 'city_id' => '51']);
        DB::table('points')->insert(['id' => '94', 'name' => 'Calle Carretas', 'cost_center' => 'ALMT0814', 'trade_name' => 'Centro Cra 7 N° 34 84', 'city_id' => '23']);
        DB::table('points')->insert(['id' => '95', 'name' => '20 de Julio', 'cost_center' => 'ALMT0815', 'trade_name' => 'Cra 6 N° 22C 66 sur.', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '96', 'name' => 'Fusagasuga', 'cost_center' => 'ALMT0816', 'trade_name' => 'Calle 8 Avda de las palmas # 6 61 Centro', 'city_id' => '46']);
        DB::table('points')->insert(['id' => '97', 'name' => 'Norte Cali', 'cost_center' => 'ALMT0817', 'trade_name' => 'Av 5 norte # 24 N 68 Local 17 (la pasarela)', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '98', 'name' => 'Tunja Centro', 'cost_center' => 'ALMT0818', 'trade_name' => 'Calle 18 # 11 58 Tunja Centro', 'city_id' => '116']);
        DB::table('points')->insert(['id' => '99', 'name' => 'Venecia 2', 'cost_center' => 'ALMT0819', 'trade_name' => 'Cra 53 N° 46 20 sur', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '100', 'name' => 'Pasto Calle 18', 'cost_center' => 'ALMT0820', 'trade_name' => 'Calle 18 # 22 40', 'city_id' => '80']);
        DB::table('points')->insert(['id' => '101', 'name' => 'Fontibon Carrera 100', 'cost_center' => 'ALMT0821', 'trade_name' => 'Carrera 100# 18 70', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '102', 'name' => 'Ventura', 'cost_center' => 'ALMT0824', 'trade_name' => 'Ventura Plaza Diagonal Santander Calle 10 y 11 Local 1 24 Sector quinta velez', 'city_id' => '33']);
        DB::table('points')->insert(['id' => '103', 'name' => 'Megamall', 'cost_center' => 'ALMT0826', 'trade_name' => 'AV Quebrada Seca N° 33A 100 Local 20 y 21 Piso 2', 'city_id' => '13']);
        DB::table('points')->insert(['id' => '104', 'name' => 'Barranquilla Centro', 'cost_center' => 'ALMT0827', 'trade_name' => 'Cra 44 # 35 36', 'city_id' => '10']);
        DB::table('points')->insert(['id' => '105', 'name' => 'Pereira Calima', 'cost_center' => 'ALMT0829', 'trade_name' => 'Calle 17 No 19 230 Local 19 La 14', 'city_id' => '82']);
        DB::table('points')->insert(['id' => '106', 'name' => 'Nuestro Uraba', 'cost_center' => 'ALMT0830', 'trade_name' => 'Cra 99 N° 84 18 Vía Carepa Local 0165 167', 'city_id' => '5']);
        DB::table('points')->insert(['id' => '107', 'name' => 'Viva Guajira', 'cost_center' => 'ALMT0831', 'trade_name' => 'Calle 15 No 18 274 De Riohacha Guajira Local 108', 'city_id' => '93']);
        DB::table('points')->insert(['id' => '108', 'name' => 'Cali Unico Dos', 'cost_center' => 'ALMT0832', 'trade_name' => 'Calle 52 N° 3 80 CC Unico Dos Local 509', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '109', 'name' => 'Aventura', 'cost_center' => 'ALMT0833', 'trade_name' => 'Cra 52 N° 66 11 Local 0254', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '110', 'name' => 'Diver Plaza 2', 'cost_center' => 'ALMT0834', 'trade_name' => 'Trav 99 N° 70 A 89 Diverplaza Local 260 A', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '111', 'name' => 'Neiva Unico', 'cost_center' => 'ALMT0836', 'trade_name' => 'UNICO. Calle 64 #1d 140 contiguo al aeropuerto local 29', 'city_id' => '76']);
        DB::table('points')->insert(['id' => '112', 'name' => 'Mayorca', 'cost_center' => 'ALMT0837', 'trade_name' => 'Av las vegas N° 50 sur 128 Local 2021 C.C Mayorca Mega Plaza', 'city_id' => '97']);
        DB::table('points')->insert(['id' => '113', 'name' => 'Calima La 14', 'cost_center' => 'ALMT0841', 'trade_name' => 'Carrera 1 calle 70 C.C la 14 de calima Sótano', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '114', 'name' => 'Bucaramanga Calle 36', 'cost_center' => 'ALMT0842', 'trade_name' => 'Carrera 18 N° 36 11', 'city_id' => '13']);
        DB::table('points')->insert(['id' => '115', 'name' => 'Duitama Centro', 'cost_center' => 'ALMT0845', 'trade_name' => 'Cll15 No 15 52', 'city_id' => '35']);
        DB::table('points')->insert(['id' => '116', 'name' => 'Centro Chia Dos', 'cost_center' => 'ALMT0847', 'trade_name' => 'Carrera 11 # 12 20 Local: 102', 'city_id' => '27']);
        DB::table('points')->insert(['id' => '117', 'name' => 'Galerias 2', 'cost_center' => 'ALMT0848', 'trade_name' => 'Calle 53 N° 21 28 Local 102', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '118', 'name' => 'Montería Centro', 'cost_center' => 'ALMT0849', 'trade_name' => 'Calle 33 N° 2 22 Local 1', 'city_id' => '75']);
        DB::table('points')->insert(['id' => '119', 'name' => 'Quirigua', 'cost_center' => 'ALMT0850', 'trade_name' => 'Transversal 94 N° 80d 69', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '120', 'name' => 'Centro Chia', 'cost_center' => 'ALMT0851', 'trade_name' => 'Av. Pradilla 900este Local: 119B', 'city_id' => '27']);
        DB::table('points')->insert(['id' => '121', 'name' => 'Titan Calle 80', 'cost_center' => 'ALMT0852', 'trade_name' => 'Carrera 80 N° 70f 49', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '122', 'name' => 'Santa Lucia', 'cost_center' => 'ALMT0856', 'trade_name' => 'Calle 8 # 48 105 Sector Ipanema', 'city_id' => '76']);
        DB::table('points')->insert(['id' => '123', 'name' => 'Unicentro V/dupar', 'cost_center' => 'ALMT0857', 'trade_name' => 'CRA 9 DIAGONAL 6 CC UNICENTRO VALLEDUPAR', 'city_id' => '119']);
        DB::table('points')->insert(['id' => '124', 'name' => 'Arrecife', 'cost_center' => 'ALMT0860', 'trade_name' => 'Carrera 4 No 11a 19 Local 104', 'city_id' => '103']);
        DB::table('points')->insert(['id' => '125', 'name' => 'Cacique', 'cost_center' => 'ALMT0863', 'trade_name' => 'Trv 93 # 34 99 Local: 384A', 'city_id' => '13']);
        DB::table('points')->insert(['id' => '126', 'name' => 'San Andresito San Jose', 'cost_center' => 'ALMT0865', 'trade_name' => 'Calle 9 # 22 20', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '127', 'name' => 'Unicentro V/cio', 'cost_center' => 'ALMT0872', 'trade_name' => 'AV 40 26c 10 Local 204 B. Nuevo Maizaro', 'city_id' => '120']);
        DB::table('points')->insert(['id' => '128', 'name' => 'Fr. Acacias', 'cost_center' => 'ALMT0873', 'trade_name' => 'Cra 17 15 52', 'city_id' => '1']);
        DB::table('points')->insert(['id' => '129', 'name' => 'Fr. Espinal', 'cost_center' => 'ALMT0875', 'trade_name' => 'CR 5 11 02 LC 2', 'city_id' => '41']);
        DB::table('points')->insert(['id' => '130', 'name' => 'Itagui', 'cost_center' => 'ALMT0877', 'trade_name' => 'Cra 52D # 80 37', 'city_id' => '55']);
        DB::table('points')->insert(['id' => '131', 'name' => 'Plaza Central', 'cost_center' => 'ALMT0878', 'trade_name' => 'Av. Calle 13 # 11 2 Local: 3 67 / 68', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '132', 'name' => 'Fr. Cali (Comertexco)', 'cost_center' => 'ALMT0879', 'trade_name' => 'Cra 8 10 60', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '133', 'name' => 'La Ceja', 'cost_center' => 'ALMT0883', 'trade_name' => 'CL 15 18 274 LC 145 C.C VIVA LA CEJA', 'city_id' => '57']);
        DB::table('points')->insert(['id' => '134', 'name' => 'Fr. B/bermeja', 'cost_center' => 'ALMT0886', 'trade_name' => 'CR 17 49 11 BRR COLOMBIA', 'city_id' => '9']);
        DB::table('points')->insert(['id' => '135', 'name' => 'Fr. Chiquinquira', 'cost_center' => 'ALMT0887', 'trade_name' => 'Cra 10 16 23 LC 101', 'city_id' => '29']);
        DB::table('points')->insert(['id' => '136', 'name' => 'Fr. Cartago', 'cost_center' => 'ALMT0888', 'trade_name' => 'C.C SANTIAGO PLAZA LC 35', 'city_id' => '24']);
        DB::table('points')->insert(['id' => '137', 'name' => 'Fr. Cali Pasoancho', 'cost_center' => 'ALMT0889', 'trade_name' => 'CL 13 43 25 P 1', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '138', 'name' => 'Fr. Puerto Lopez', 'cost_center' => 'ALMT0890', 'trade_name' => 'CR 7A 4 80 BRR SANTANDER', 'city_id' => '90']);
        DB::table('points')->insert(['id' => '139', 'name' => 'Antares Soacha', 'cost_center' => 'ALMT0891', 'trade_name' => 'Carrera 7 # 30B 139 Local: 1 113', 'city_id' => '110']);
        DB::table('points')->insert(['id' => '140', 'name' => 'La Colina', 'cost_center' => 'ALMT0892', 'trade_name' => 'Carrera 58D # 146 51 Local: 320', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '141', 'name' => 'Viva Barranquilla', 'cost_center' => 'ALMT0893', 'trade_name' => 'Carrera 51b # 87 50 Local 340', 'city_id' => '10']);
        DB::table('points')->insert(['id' => '142', 'name' => 'Campanario', 'cost_center' => 'ALMT0894', 'trade_name' => 'Carrera 9 # 24a norte 21 Local 125', 'city_id' => '86']);
        DB::table('points')->insert(['id' => '143', 'name' => 'Sogamoso', 'cost_center' => 'ALMT0895', 'trade_name' => 'Calle 11 # 11 45 Edf. San Judas Tadeo', 'city_id' => '111']);
        DB::table('points')->insert(['id' => '144', 'name' => 'Fr. La Dorada', 'cost_center' => 'ALMT0904', 'trade_name' => 'CL 13 CR 1 MOLL SANTANA DEL RIO', 'city_id' => '58']);
        DB::table('points')->insert(['id' => '145', 'name' => 'Fr. Barbosa', 'cost_center' => 'ALMT0905', 'trade_name' => 'CL 7 8 40', 'city_id' => '8']);
        DB::table('points')->insert(['id' => '146', 'name' => 'Fr. Aguachica', 'cost_center' => 'ALMT0906', 'trade_name' => 'CR 14 5 34 BRR EL CENTRO', 'city_id' => '2']);
        DB::table('points')->insert(['id' => '147', 'name' => 'Fr. Facatativa', 'cost_center' => 'ALMT0908', 'trade_name' => 'CR 4 6 25', 'city_id' => '42']);
        DB::table('points')->insert(['id' => '148', 'name' => 'Cali Unico Tres', 'cost_center' => 'ALMT0909', 'trade_name' => 'CL 52 3 29 LC 12C', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '149', 'name' => 'Fr. Ubate', 'cost_center' => 'ALMT0911', 'trade_name' => 'CL 10 6 21 UBATE', 'city_id' => '118']);
        DB::table('points')->insert(['id' => '150', 'name' => 'Caldas 2', 'cost_center' => 'ALMT0913', 'trade_name' => 'Cr. 49 N° 134 sur 81', 'city_id' => '19']);
        DB::table('points')->insert(['id' => '151', 'name' => 'NO APLICA', 'cost_center' => 'ALMT0915', 'trade_name' => 'CR 126A 137-07 SUBA', 'city_id' => '63']);
        DB::table('points')->insert(['id' => '152', 'name' => 'Fr. Libano', 'cost_center' => 'ALMT0916', 'trade_name' => 'Cl 4 N° 8 56', 'city_id' => '64']);
        DB::table('points')->insert(['id' => '153', 'name' => 'Restrepo Dos', 'cost_center' => 'ALMT0917', 'trade_name' => 'Carrera 19 # 16 32 Sur', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '154', 'name' => 'Cosmocentro', 'cost_center' => 'ALMT0918', 'trade_name' => 'Carrera 33 N° 51 – 119, LOCAL 101 102 103 104', 'city_id' => '13']);
        DB::table('points')->insert(['id' => '155', 'name' => 'Camino Real', 'cost_center' => 'ALMT0919', 'trade_name' => 'Cra 46 # 52 85 Local 130', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '156', 'name' => 'Fr. Cajica', 'cost_center' => 'ALMT0920', 'trade_name' => 'CL 4 6 37', 'city_id' => '17']);
        DB::table('points')->insert(['id' => '157', 'name' => 'Fr. Arauca', 'cost_center' => 'ALMT0921', 'trade_name' => 'Cra 18 N° 21 46 Br. Córdoba', 'city_id' => '6']);
        DB::table('points')->insert(['id' => '158', 'name' => 'Fr. Buenaventura', 'cost_center' => 'ALMT0922', 'trade_name' => 'Calle 3 N° 3 92', 'city_id' => '14']);
        DB::table('points')->insert(['id' => '159', 'name' => 'Fr. La Ceja', 'cost_center' => 'ALMT0923', 'trade_name' => 'CL 21 20 13', 'city_id' => '57']);
        DB::table('points')->insert(['id' => '160', 'name' => 'Fr. Sahagun', 'cost_center' => 'ALMT0924', 'trade_name' => 'Por', 'city_id' => '98']);
        DB::table('points')->insert(['id' => '161', 'name' => 'Fr. Buga', 'cost_center' => 'ALMT0925', 'trade_name' => 'Cra 14 6 20 Los Portales', 'city_id' => '15']);
        DB::table('points')->insert(['id' => '162', 'name' => 'Fr. Palmira', 'cost_center' => 'ALMT0927', 'trade_name' => 'Cra 26 N° 29 14 Local 26', 'city_id' => '78']);
        DB::table('points')->insert(['id' => '163', 'name' => 'Fr. Villaluz', 'cost_center' => 'ALMT0928', 'trade_name' => 'CR 77 A 63 F 34 LC 1', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '164', 'name' => 'Fr. Melgar', 'cost_center' => 'ALMT0929', 'trade_name' => 'CR 24 7 54 LC 5', 'city_id' => '72']);
        DB::table('points')->insert(['id' => '165', 'name' => 'Fr. Lorica', 'cost_center' => 'ALMT0930', 'trade_name' => 'CL 3 24 29 Br. Cascajal', 'city_id' => '65']);
        DB::table('points')->insert(['id' => '166', 'name' => 'Mayorca Dos', 'cost_center' => 'ALMT0931', 'trade_name' => 'Av las Vegas # 50 sur 128 Local 2021', 'city_id' => '97']);
        DB::table('points')->insert(['id' => '167', 'name' => 'Nuestro Atlántico', 'cost_center' => 'ALMT0932', 'trade_name' => 'CL 63 13 71 Local 1013 Soledad', 'city_id' => '112']);
        DB::table('points')->insert(['id' => '168', 'name' => 'Fr. Giron', 'cost_center' => 'ALMT0935', 'trade_name' => 'Cl 41 22 80 Br El Poblado', 'city_id' => '50']);
        DB::table('points')->insert(['id' => '169', 'name' => 'Mall Plaza Cartagena', 'cost_center' => 'ALMT0936', 'trade_name' => 'C.C Mall Plaza Av. Pedro De Heredia 13 65 Lc 122 123 Brr Chambacú', 'city_id' => '23']);
        DB::table('points')->insert(['id' => '170', 'name' => 'Plaza del Rio', 'cost_center' => 'ALMT0937', 'trade_name' => 'C.C Plaza Del Rio Local 123 Calle 100 Carrera 100 Via Principal Apartado', 'city_id' => '5']);
        DB::table('points')->insert(['id' => '171', 'name' => 'Fr. Calarca', 'cost_center' => 'ALMT0938', 'trade_name' => 'Cra 25 32 30', 'city_id' => '18']);
        DB::table('points')->insert(['id' => '172', 'name' => 'Fr. Santa Rosa de Cabal', 'cost_center' => 'ALMT0939', 'trade_name' => 'Cl 13 13 38 LC 1 FR 31', 'city_id' => '104']);
        DB::table('points')->insert(['id' => '173', 'name' => 'Fr. Verbenal', 'cost_center' => 'ALMT0940', 'trade_name' => 'CL 183 15 29 VERBENAL', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '174', 'name' => 'Ferias', 'cost_center' => 'ALMT0942', 'trade_name' => 'Avenida Calle 72 # 68 H 27', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '175', 'name' => 'Villavicencio Cra 30', 'cost_center' => 'ALMT0943', 'trade_name' => 'Cra 30 # 36 76', 'city_id' => '120']);
        DB::table('points')->insert(['id' => '176', 'name' => 'San Silvestre', 'cost_center' => 'ALMT0944', 'trade_name' => 'Diagonal 56 #18a 88 Local 214', 'city_id' => '9']);
        DB::table('points')->insert(['id' => '177', 'name' => 'Franquicia San Andres Islas', 'cost_center' => 'ALMT0947', 'trade_name' => 'AV LIBERTADORES CC CAPRI LC 32 ESQ', 'city_id' => '99']);
        DB::table('points')->insert(['id' => '178', 'name' => 'Fr. Tocancipa', 'cost_center' => 'ALMT0948', 'trade_name' => 'CR 7 7 43', 'city_id' => '114']);
        DB::table('points')->insert(['id' => '179', 'name' => 'Fr. La Mesa', 'cost_center' => 'ALMT0949', 'trade_name' => 'CL 6 21 03 LC 1', 'city_id' => '60']);
        DB::table('points')->insert(['id' => '180', 'name' => 'Fr. El Carmen de Viboral', 'cost_center' => 'ALMT0950', 'trade_name' => 'CL 27 31 19 LC 102', 'city_id' => '37']);
        DB::table('points')->insert(['id' => '181', 'name' => 'Multiplaza la Felicidad', 'cost_center' => 'ALMT0951', 'trade_name' => 'Calle 19a No. 72 47 Local B 133', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '182', 'name' => 'Nuestro Monteria', 'cost_center' => 'ALMT0952', 'trade_name' => 'Calle 29 20 337 LC L 0295 Nuestro Montería', 'city_id' => '75']);
        DB::table('points')->insert(['id' => '183', 'name' => 'Gran Plaza Bosa', 'cost_center' => 'ALMT0953', 'trade_name' => 'Gran Plaza Bosa Local 158 Calle 65 sur No 78 H 51', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '184', 'name' => 'Fr. Ciudad Montes', 'cost_center' => 'ALMT0960', 'trade_name' => 'CL 8 SUR 34 27', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '185', 'name' => 'Fr. Garzon', 'cost_center' => 'ALMT0965', 'trade_name' => 'CR 10 7 32', 'city_id' => '47']);
        DB::table('points')->insert(['id' => '186', 'name' => 'Fr. Girardota', 'cost_center' => 'ALMT0967', 'trade_name' => 'CL 6 14 23', 'city_id' => '49']);
        DB::table('points')->insert(['id' => '187', 'name' => 'Fr. Tame', 'cost_center' => 'ALMT0968', 'trade_name' => 'CL 14 16 40', 'city_id' => '113']);
        DB::table('points')->insert(['id' => '188', 'name' => 'Fr. Puerto Boyaca', 'cost_center' => 'ALMT0969', 'trade_name' => 'CL 12 4 18 LC 3', 'city_id' => '89']);
        DB::table('points')->insert(['id' => '189', 'name' => 'Fr. Aguazul', 'cost_center' => 'ALMT0970', 'trade_name' => 'CL 9 17 67', 'city_id' => '3']);
        DB::table('points')->insert(['id' => '190', 'name' => 'Fr. Pereira Cuba', 'cost_center' => 'ALMT0971', 'trade_name' => 'CL 69 25 08 LC 102', 'city_id' => '82']);
        DB::table('points')->insert(['id' => '191', 'name' => 'Chipichape', 'cost_center' => 'ALMT0973', 'trade_name' => 'Centro Comercial Chipichape Local 213 Bodega 2 Calle 38 No 6 Norte', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '192', 'name' => 'Fr. Ocaña', 'cost_center' => 'ALMT0974', 'trade_name' => 'Cr 13 11 40 Br. El Centro', 'city_id' => '77']);
        DB::table('points')->insert(['id' => '193', 'name' => 'Santa Librada', 'cost_center' => 'ALMT0976', 'trade_name' => 'Cra 14 75 37 S', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '194', 'name' => 'Fr. Zarzal', 'cost_center' => 'ALMT0978', 'trade_name' => 'CR 11 8 87', 'city_id' => '124']);
        DB::table('points')->insert(['id' => '195', 'name' => 'Fr. Sevilla', 'cost_center' => 'ALMT0979', 'trade_name' => 'CR 51 52 49', 'city_id' => '108']);
        DB::table('points')->insert(['id' => '196', 'name' => 'Fr. Mariquita', 'cost_center' => 'ALMT0980', 'trade_name' => 'CR 5 5 71 LC 1', 'city_id' => '70']);
        DB::table('points')->insert(['id' => '197', 'name' => 'Fr. Castilla', 'cost_center' => 'ALMT0984', 'trade_name' => 'CR 78 8 46 LC 01', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '198', 'name' => 'Fr. Chinchina', 'cost_center' => 'ALMT0987', 'trade_name' => 'CR 8 12 55', 'city_id' => '28']);
        DB::table('points')->insert(['id' => '199', 'name' => 'Fr. Copacabana', 'cost_center' => 'ALMT0988', 'trade_name' => 'Cr 53 49 66', 'city_id' => '32']);
        DB::table('points')->insert(['id' => '200', 'name' => 'Fr. Prado', 'cost_center' => 'ALMT0989', 'trade_name' => 'CL 129 50 A 24', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '201', 'name' => 'Fr. Marinilla', 'cost_center' => 'ALMT0990', 'trade_name' => 'Cra 34 28 B 41 LC 102 Primer Piso Ed Victoriano', 'city_id' => '69']);
        DB::table('points')->insert(['id' => '202', 'name' => 'Santa Helenita', 'cost_center' => 'ALMT0991', 'trade_name' => 'Avenida Calle 72 No 76 63', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '203', 'name' => 'Fr. Sabanalarga', 'cost_center' => 'ALMT0992', 'trade_name' => 'CL 19 19 08 LC 5', 'city_id' => '96']);
        DB::table('points')->insert(['id' => '204', 'name' => 'Multicentro Ibague', 'cost_center' => 'ALMT0995', 'trade_name' => 'Multicentro Local 234 KR 5 61 41', 'city_id' => '53']);
        DB::table('points')->insert(['id' => '205', 'name' => 'Valledupar Centro Dos', 'cost_center' => 'ALMT0996', 'trade_name' => 'CL 16 B 7 48 Local 4', 'city_id' => '119']);
        DB::table('points')->insert(['id' => '206', 'name' => 'Casa Blanca Madrid', 'cost_center' => 'ALMT0997', 'trade_name' => 'Cl 7 N 1 A 91 Este Madrid LC 04 5', 'city_id' => '66']);
        DB::table('points')->insert(['id' => '207', 'name' => 'Fr. Santander de Quilichao', 'cost_center' => 'ALMT0998', 'trade_name' => 'CL 4 10 67 Br. Centro', 'city_id' => '105']);
        DB::table('points')->insert(['id' => '208', 'name' => 'Fr. El Banco Magdalena', 'cost_center' => 'ALMT0999', 'trade_name' => 'CL 7 4 61', 'city_id' => '36']);
        DB::table('points')->insert(['id' => '209', 'name' => 'Guacari', 'cost_center' => 'ALMT1000', 'trade_name' => 'CL 28 # 25B 97 Local 1 126 Parque Comercial Guacari', 'city_id' => '109']);
        DB::table('points')->insert(['id' => '210', 'name' => 'Fr. Puerto Berrio', 'cost_center' => 'ALMT1001', 'trade_name' => 'CR 9 CON CL 50 02', 'city_id' => '88']);
        DB::table('points')->insert(['id' => '211', 'name' => 'Llano Grande', 'cost_center' => 'ALMT1002', 'trade_name' => 'Cl 31 No. 44 239 local 430 431', 'city_id' => '78']);
        DB::table('points')->insert(['id' => '212', 'name' => 'Yopal Cra 19', 'cost_center' => 'ALMT1003', 'trade_name' => 'Cra 19 no. 8 34', 'city_id' => '122']);
        DB::table('points')->insert(['id' => '213', 'name' => 'Fr. La Estrella', 'cost_center' => 'ALMT1004', 'trade_name' => 'CL 87 Sur No 59 115 Int 103', 'city_id' => '59']);
        DB::table('points')->insert(['id' => '214', 'name' => 'Fr. Quimbaya', 'cost_center' => 'ALMT1005', 'trade_name' => 'CR 6 18 32', 'city_id' => '92']);
        DB::table('points')->insert(['id' => '215', 'name' => 'Fr. Caucasia', 'cost_center' => 'ALMT1007', 'trade_name' => 'Cl 20 # 13 63 av fajonal', 'city_id' => '25']);
        DB::table('points')->insert(['id' => '216', 'name' => 'Fr. Candelaria', 'cost_center' => 'ALMT1008', 'trade_name' => 'Kr 7 8 58 Br. Maria Auxiliadora Candelaria', 'city_id' => '21']);
        DB::table('points')->insert(['id' => '217', 'name' => 'Fr. La Union', 'cost_center' => 'ALMT1010', 'trade_name' => 'Cra 15 N° 16 43 Local 1', 'city_id' => '62']);
        DB::table('points')->insert(['id' => '218', 'name' => 'Terreros', 'cost_center' => 'ALMT1013', 'trade_name' => 'Cra 1 N° 38 53 Ventura Terreros LC 109', 'city_id' => '110']);
        DB::table('points')->insert(['id' => '219', 'name' => 'Poblado Plaza', 'cost_center' => 'ALMT1014', 'trade_name' => 'CL 15 No.11c 75 Via oriental Km21 Santo Tomas Atlántico', 'city_id' => '106']);
        DB::table('points')->insert(['id' => '220', 'name' => 'Fr. Mesitas', 'cost_center' => 'ALMT1015', 'trade_name' => 'Cra 4 No 4 84 Barrio La Castellana', 'city_id' => '39']);
        DB::table('points')->insert(['id' => '221', 'name' => 'Fr. Montelibano', 'cost_center' => 'ALMT1016', 'trade_name' => 'Cl 17 6 39 Lc 108 CC San Jose Brr. Centro', 'city_id' => '74']);
        DB::table('points')->insert(['id' => '222', 'name' => 'Prado', 'cost_center' => 'ALMT1017', 'trade_name' => 'Calle 53 N° 46 192 Local 006 Sotano C.C Portal del Prado', 'city_id' => '10']);
        DB::table('points')->insert(['id' => '223', 'name' => 'Fr. Tuquerres', 'cost_center' => 'ALMT1018', 'trade_name' => 'Calle 17 No. 14 23', 'city_id' => '117']);
        DB::table('points')->insert(['id' => '224', 'name' => 'Fr. Sabaneta', 'cost_center' => 'ALMT1023', 'trade_name' => 'Cra 46 no 74 sur 19', 'city_id' => '97']);
        DB::table('points')->insert(['id' => '225', 'name' => 'Fr. San Jose del Guaviare', 'cost_center' => 'ALMT1024', 'trade_name' => 'Cl 8 # 22 104 Centro', 'city_id' => '102']);
        DB::table('points')->insert(['id' => '226', 'name' => 'Fr. San Andres de Tumaco', 'cost_center' => 'ALMT1027', 'trade_name' => 'Cra 8VA # 13 112 DG Coliceo del pueblo', 'city_id' => '100']);
        DB::table('points')->insert(['id' => '227', 'name' => 'Megamall Valledupar', 'cost_center' => 'ALMT1108', 'trade_name' => 'Calle 16 # 19b 56 Local 25', 'city_id' => '119']);
        DB::table('points')->insert(['id' => '228', 'name' => 'Dos Quebradas Unico', 'cost_center' => 'ALMT1109', 'trade_name' => 'Kra 16 Cl 24 Esquina Av simon bolivar Local 32, Unico Dosquebradas', 'city_id' => '34']);
        DB::table('points')->insert(['id' => '229', 'name' => 'La 93', 'cost_center' => 'ALMT1121', 'trade_name' => 'Cra 15 N° 92 73', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '230', 'name' => 'Pradera Dos', 'cost_center' => 'ALMT1123', 'trade_name' => 'AV CL 9 60 70 Local 210', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '231', 'name' => 'Paseo Bolívar', 'cost_center' => 'ALMT1125', 'trade_name' => 'Calle 34 # 41 19', 'city_id' => '10']);
        DB::table('points')->insert(['id' => '232', 'name' => 'Fr. Jamundi', 'cost_center' => 'ALMT1127', 'trade_name' => 'Cra 11 # 11 34 B. Juan de Ampudia', 'city_id' => '56']);
        DB::table('points')->insert(['id' => '233', 'name' => 'Fr. Anserma', 'cost_center' => 'ALMT1128', 'trade_name' => 'Cra 4 N° 8 37', 'city_id' => '4']);
        DB::table('points')->insert(['id' => '234', 'name' => 'Fr. Cimitarra', 'cost_center' => 'ALMT1129', 'trade_name' => 'Calle 6 # 5 33 B. Centro', 'city_id' => '31']);
        DB::table('points')->insert(['id' => '235', 'name' => 'Fr. Caicedonia', 'cost_center' => 'ALMT1150', 'trade_name' => 'Cra 16 N° 9 39', 'city_id' => '16']);
        DB::table('points')->insert(['id' => '236', 'name' => 'La Central', 'cost_center' => 'ALMT1151', 'trade_name' => 'Cl 49 N° 21 38 Local 0214 B. Buenos Aires', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '237', 'name' => 'Buenavista', 'cost_center' => 'ALMT1156', 'trade_name' => 'Calle 14 Diagonal 34 01 Local 107', 'city_id' => '103']);
        DB::table('points')->insert(['id' => '238', 'name' => 'Fr. Cienaga', 'cost_center' => 'ALMT1157', 'trade_name' => 'Calle 12 # 11 40 Local 1', 'city_id' => '30']);
        DB::table('points')->insert(['id' => '239', 'name' => 'Ipiales Centro', 'cost_center' => 'ALMT1159', 'trade_name' => 'Carrera 6 # 13 87', 'city_id' => '54']);
        DB::table('points')->insert(['id' => '240', 'name' => 'Fr. La Plata', 'cost_center' => 'ALMT1161', 'trade_name' => 'CL 6 # 3 56', 'city_id' => '61']);
        DB::table('points')->insert(['id' => '241', 'name' => 'Carnaval', 'cost_center' => 'ALMT1163', 'trade_name' => 'CL 30 13 65 LC 1121', 'city_id' => '112']);
        DB::table('points')->insert(['id' => '242', 'name' => 'Mall Plaza Manizales', 'cost_center' => 'ALMT1164', 'trade_name' => 'Cra 11Bis 57 E 76 LC. A 2033', 'city_id' => '68']);
        DB::table('points')->insert(['id' => '243', 'name' => 'Ipiales Centro Dos', 'cost_center' => 'ALMT1165', 'trade_name' => 'Cra 5 8 58 Plaza 20 De Julio ED MT Orang', 'city_id' => '54']);
        DB::table('points')->insert(['id' => '244', 'name' => 'Outlet La Floresta', 'cost_center' => 'ALMT1166', 'trade_name' => 'CR 69 98 A 45', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '245', 'name' => 'Viva Envigado', 'cost_center' => 'ALMT1167', 'trade_name' => 'Cra 48 #32B Sur – 139 LC 227', 'city_id' => '40']);
        DB::table('points')->insert(['id' => '246', 'name' => 'Fr. Galan', 'cost_center' => 'ALMT1172', 'trade_name' => 'Cra 56 4 C 18 Br. Galan', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '247', 'name' => 'Cosmocentro Cali', 'cost_center' => 'ALMT1175', 'trade_name' => 'Calle 5 No. 50 103 Local 2G', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '248', 'name' => 'Viva Tunja', 'cost_center' => 'ALMT1180', 'trade_name' => 'AV Universitaria 50 – 21 Viva Local 128', 'city_id' => '116']);
        DB::table('points')->insert(['id' => '249', 'name' => 'Moda Prime', 'cost_center' => 'ALMT1181', 'trade_name' => 'CL 16 55 129 LC 106 C.C De moda outlet', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '250', 'name' => 'Fr. Roma', 'cost_center' => 'ALMT1182', 'trade_name' => 'Cra 80 N° 47 59', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '251', 'name' => 'Fr. Roldanillo', 'cost_center' => 'ALMT1183', 'trade_name' => 'Calle 9 # 5 71 B. Centro', 'city_id' => '95']);
        DB::table('points')->insert(['id' => '252', 'name' => 'Bocagrande', 'cost_center' => 'ALMT1184', 'trade_name' => 'Cra 2 # 06 105 Local 0104', 'city_id' => '23']);
        DB::table('points')->insert(['id' => '253', 'name' => 'Fr. Chaparral', 'cost_center' => 'ALMT1185', 'trade_name' => 'Cra 9 # 8 65', 'city_id' => '26']);
        DB::table('points')->insert(['id' => '254', 'name' => 'Fr. Puerto Asis', 'cost_center' => 'ALMT1187', 'trade_name' => 'Cra 18 No. 11 91', 'city_id' => '87']);
        DB::table('points')->insert(['id' => '255', 'name' => 'Gran Plaza Ensueño', 'cost_center' => 'ALMT1188', 'trade_name' => 'Calle 59C sur 61 21', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '256', 'name' => 'Fr. Pamplona', 'cost_center' => 'ALMT1189', 'trade_name' => 'Cra 5 8 02/14 Local 1 y 2 Barrio Centro Pamplona', 'city_id' => '79']);
        DB::table('points')->insert(['id' => '257', 'name' => 'Fr. Quibdo', 'cost_center' => 'ALMT1190', 'trade_name' => 'Cl 25 4 40 Lc 108 Brr Pan de Yuca', 'city_id' => '91']);
        DB::table('points')->insert(['id' => '258', 'name' => 'Fr. El Cerrito', 'cost_center' => 'ALMT1192', 'trade_name' => 'CL 7 # 12 29', 'city_id' => '38']);
        DB::table('points')->insert(['id' => '259', 'name' => 'Girardot Cra 10', 'cost_center' => 'ALMT1193', 'trade_name' => 'Cra 10 # 14 75 C.C Pasaje Real Local 3 y 4', 'city_id' => '48']);
        DB::table('points')->insert(['id' => '260', 'name' => 'Fr. Saravena', 'cost_center' => 'ALMT1195', 'trade_name' => 'CL 27 13 55 BRR Centro', 'city_id' => '107']);
        DB::table('points')->insert(['id' => '261', 'name' => 'Gran estacion', 'cost_center' => 'ALMT1196', 'trade_name' => 'Carrera 60 # 24 9 Local: L1 31 Costado Esfera.', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '262', 'name' => 'Yoi Toberin', 'cost_center' => 'ALMT1197', 'trade_name' => 'CL 164 22 42', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '263', 'name' => 'Yoi Gran Plaza Ensueño', 'cost_center' => 'ALMT1198', 'trade_name' => 'Cr 51 59 C sur 93 Lc 159', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '264', 'name' => 'Cali Luna', 'cost_center' => 'ALMT1199', 'trade_name' => 'Calle 13 23d 29', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '265', 'name' => 'Quindio 2', 'cost_center' => 'ALMT1200', 'trade_name' => 'cc portal del quindio local 4 piso 1', 'city_id' => '7']);
        DB::table('points')->insert(['id' => '266', 'name' => 'Alcaravan', 'cost_center' => 'ALMT1201', 'trade_name' => 'Cl 30 entre Cra 28 y 29 Gran plaza alcaravan Local 074 A y B', 'city_id' => '122']);
        DB::table('points')->insert(['id' => '267', 'name' => 'Jardin Plaza', 'cost_center' => 'ALMT1203', 'trade_name' => 'Jardín Plaza Local L 74 Anillo Vial Oriental Vía La Gasapa', 'city_id' => '33']);
        DB::table('points')->insert(['id' => '268', 'name' => 'Plaza de las Americas', 'cost_center' => 'ALMT1204', 'trade_name' => 'CR 71D 6 94 SUR Plaza de las Américas Local 1025', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '269', 'name' => 'Fr. Bosa', 'cost_center' => 'ALMT1205', 'trade_name' => 'CRA 88 C 56 68 Sur Barrio Bosa', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '270', 'name' => 'Villeta', 'cost_center' => 'ALMT1206', 'trade_name' => 'CL 5 # 6 52 BRR Centro', 'city_id' => '121']);
        DB::table('points')->insert(['id' => '271', 'name' => 'Yoi Exito Chapinero', 'cost_center' => 'ALMT1207', 'trade_name' => 'CL 52 13 70', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '272', 'name' => 'Fr. Honda', 'cost_center' => 'ALMT1208', 'trade_name' => 'CL 9 9 116 LC 2 AV CENTENARIO', 'city_id' => '52']);
        DB::table('points')->insert(['id' => '273', 'name' => 'La Castellana', 'cost_center' => 'ALMT1209', 'trade_name' => 'AV Pedro de heredia, CL 30 30 31 Sector Villa Sandra LC 93 94', 'city_id' => '23']);
        DB::table('points')->insert(['id' => '274', 'name' => 'Yoi Portal Quindio', 'cost_center' => 'ALMT1211', 'trade_name' => 'Portal del quindio nivel 3 local 13 14 15', 'city_id' => '7']);
        DB::table('points')->insert(['id' => '275', 'name' => 'Fr. Boita', 'cost_center' => 'ALMT1212', 'trade_name' => 'Calle 45 sur # 72 L 28', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '276', 'name' => 'Fr. Engativa', 'cost_center' => 'ALMT1213', 'trade_name' => 'Cra 117 63 k 11', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '277', 'name' => 'Fr. Sabanalarga', 'cost_center' => 'ALMT1214', 'trade_name' => 'CL 19 19 08 LC 5', 'city_id' => '96']);
        DB::table('points')->insert(['id' => '278', 'name' => 'Las Nieves', 'cost_center' => 'ALMT1215', 'trade_name' => 'Cra 7# 19 56', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '279', 'name' => 'Atlantis', 'cost_center' => 'ALMT1216', 'trade_name' => 'Calle 81#13 05 Local : L301B, L302, LC302B', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '280', 'name' => 'Fr. Maicao', 'cost_center' => 'ALMT1217', 'trade_name' => 'CL 12 9 09 BRR CENTRO', 'city_id' => '67']);
        DB::table('points')->insert(['id' => '281', 'name' => 'Yoi Atlantis', 'cost_center' => 'ALMT1218', 'trade_name' => 'CL 81 13 05 LC 101 102', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '282', 'name' => 'Fr. Siete de agosto', 'cost_center' => 'ALMT1219', 'trade_name' => 'CL 64 # 24 10', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '283', 'name' => 'Yoi Gran Plaza Soacha', 'cost_center' => 'ALMT1220', 'trade_name' => 'Cra 7 # 30 B 139 CC. Gran plaza Soacha Local 163', 'city_id' => '110']);
        DB::table('points')->insert(['id' => '284', 'name' => 'Plaza Central 2', 'cost_center' => 'ALMT1221', 'trade_name' => 'CRA 65 # 11 90 CC Plaza Central Local N: 2 8', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '285', 'name' => 'Montevideo', 'cost_center' => 'ALMT1222', 'trade_name' => 'CL 19 # 69 86 local 6', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '286', 'name' => 'Fr. Piedecuesta', 'cost_center' => 'ALMT1227', 'trade_name' => 'Cra 8 # 8 90 local 1 centro', 'city_id' => '84']);
        DB::table('points')->insert(['id' => '287', 'name' => 'Yoi Gran Plaza Florencia', 'cost_center' => 'ALMT1228', 'trade_name' => 'CLL 3 BIS # 6A-14 LC 244, 245 Y 246', 'city_id' => '22']);
        DB::table('points')->insert(['id' => '288', 'name' => 'Yoi Gran Plaza Bosa', 'cost_center' => 'ALMT1229', 'trade_name' => 'CLL 65 SUR N 78H 51', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '289', 'name' => 'Fr. San Gil (Saroga)', 'cost_center' => 'ALMT1230', 'trade_name' => 'CL 10 12 184 C.C EL PUENTE LOCAL 141', 'city_id' => '101']);
        DB::table('points')->insert(['id' => '290', 'name' => 'San Diego', 'cost_center' => 'ALMT1231', 'trade_name' => 'CL 34 46 66 C.C San Diego Local 1551', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '291', 'name' => 'Yoi Jardin Plaza Cucuta', 'cost_center' => 'ALMT1232', 'trade_name' => 'Anillo Vial Via Oriental Sector la gasapa Local Nº L76A', 'city_id' => '33']);
        DB::table('points')->insert(['id' => '292', 'name' => 'Fr. Parque Caldas', 'cost_center' => 'ALMT1233', 'trade_name' => 'Cra 22 29 29 CC Comercial Parque Caldas Local I 17', 'city_id' => '68']);
        DB::table('points')->insert(['id' => '293', 'name' => 'Yoi Portal 80', 'cost_center' => 'ALMT1234', 'trade_name' => 'AV 80 100 52 CC PORTAL 80 LC 3-003', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '294', 'name' => 'Yoi Plaza Central', 'cost_center' => 'ALMT1235', 'trade_name' => 'Cra 13 # 98 21 Local 1 65', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '295', 'name' => 'Fr. Bulevar Niza', 'cost_center' => 'ALMT1236', 'trade_name' => 'CL 127 D 58 18 C.C Bulevar Niza Local 10', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '296', 'name' => 'Yoi Cali Unico', 'cost_center' => 'ALMT1237', 'trade_name' => 'CL 47 3 125 LC 435', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '297', 'name' => 'Yoi Exito La Flora', 'cost_center' => 'ALMT1238', 'trade_name' => 'AV 3 F NORTE 52 N 46 LOCAL L0204A', 'city_id' => '20']);
        DB::table('points')->insert(['id' => '298', 'name' => 'Plaza Nariño', 'cost_center' => 'ALMT1240', 'trade_name' => 'CL 24 18 06', 'city_id' => '80']);
        DB::table('points')->insert(['id' => '299', 'name' => 'Yoi Exito Unicentro Medellin', 'cost_center' => 'ALMT1241', 'trade_name' => 'CR 66 B 34 A 76', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '300', 'name' => 'Yoi Puerta del Norte', 'cost_center' => 'ALMT1242', 'trade_name' => 'DG 55 34 67 EXITO PUERTA DEL NORTE', 'city_id' => '11']);
        DB::table('points')->insert(['id' => '301', 'name' => 'Yoi Exito Niza', 'cost_center' => 'ALMT1243', 'trade_name' => 'CR 53 119 04 Exito Niza', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '302', 'name' => 'Yoi Exito Norte 170', 'cost_center' => 'ALMT1244', 'trade_name' => 'AV KR 45 # 173 - 60', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '303', 'name' => 'Yoi Exito Colombia', 'cost_center' => 'ALMT1245', 'trade_name' => 'CRA 66 N 49-01', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '304', 'name' => 'Fr. Paz de ariporo', 'cost_center' => 'ALMT1246', 'trade_name' => 'Calle 9 N. 8 60 Brr Centro', 'city_id' => '81']);
        DB::table('points')->insert(['id' => '305', 'name' => 'Yoi Suba', 'cost_center' => 'ALMT1248', 'trade_name' => 'CL 145 105 B 58', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '306', 'name' => 'Yoi Exito Cl 80', 'cost_center' => 'ALMT1249', 'trade_name' => 'Cra. 59a # 79 30', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '307', 'name' => 'Fr. Mocoa', 'cost_center' => 'ALMT1251', 'trade_name' => 'CL 9 CR 4 ESQUINA BRR JOSE MARIA HERNANDEZ', 'city_id' => '73']);
        DB::table('points')->insert(['id' => '308', 'name' => 'Fr. Palenque', 'cost_center' => 'ALMT1252', 'trade_name' => 'CL 42 SUR 78A 41', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '309', 'name' => 'Yoi Exito Colina', 'cost_center' => 'ALMT1255', 'trade_name' => 'AV BOYACA 146 A 25', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '310', 'name' => 'Fr. Florida blanca', 'cost_center' => 'ALMT1256', 'trade_name' => 'CL 30 10E 47 BRR LA CUMBRE', 'city_id' => '44']);
        DB::table('points')->insert(['id' => '311', 'name' => 'Fr. Villas de granada', 'cost_center' => 'ALMT1257', 'trade_name' => 'KR 110a # 77a- 92', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '312', 'name' => 'Yoi Exito Poblado', 'cost_center' => 'ALMT1259', 'trade_name' => 'CL 10 43 E 135', 'city_id' => '71']);
        DB::table('points')->insert(['id' => '313', 'name' => 'Fr. Modelia', 'cost_center' => 'ALMT1266', 'trade_name' => 'AV CL 24 75 40', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '314', 'name' => 'Fr. Subazar', 'cost_center' => 'ALMT1270', 'trade_name' => 'CR 91 134 A 36', 'city_id' => '12']);
        DB::table('points')->insert(['id' => '315', 'name' => 'Fr. San Cristobal Norte', 'cost_center' => 'ALMT1272', 'trade_name' => 'CL 161 A 8 C 07', 'city_id' => '12']);

    }
}
